### ISSUE TITLE
Forslag: mulighed for at hvert redirect har statistik

### ISSUE THREAD

**Issue by rpjengaard** [skybrud/Skybrud.Umbraco.Redirects#1]
I første omgang ville det være rart bare med en counter der incrementes hver gang redirectet rammes.

**Comment by abjerner** [comment]
Closing this for now as it should ideally be a separate package on top of this package.

@rpjengaard if we have clients that are actually requesting this, please help prioritizing this internally, so we have have a look at it 😉
