### ISSUE TITLE
Save button isn't localized

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#101]
After installing v2.0.9 I noticed localization of save button is missing.

![image](https://user-images.githubusercontent.com/2919859/132297238-9234b9f9-35d7-45fd-aebf-6c10d271ce1a.png)

It seems to use `general_save` key, https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/644684c5707db3f6d7e53dd8155fb97f86a06d3c/src/Skybrud.Umbraco.Redirects/App_Plugins/Skybrud.Umbraco.Redirects/Scripts/Controllers/Dialogs/Redirect.js#L25

but the key doesn't exists in core. However there's a `buttons_save` key.

https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI/Umbraco/config/lang/en.xml#L139

https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml#L138

https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI/Umbraco/config/lang/da.xml#L139

It seems changes was made regarding this in https://github.com/skybrud/Skybrud.Umbraco.Redirects/commit/644684c5707db3f6d7e53dd8155fb97f86a06d3c#diff-3113e72777f3e97a58ff38ff3ad35724cdcc70d6e424774e43358b340533f6d4

It could probably just use `redirects_save` key instead.

**Comment by abjerner** [comment]
Thanks for reporting @bjarnef 👍 

Seems a bit weird. I'm pretty sure it worked when I tested locally. Maybe some other package added the `general_save` key 😮 

I'll look into this 😉

**Comment by bjarnef** [comment]
No, the redirects package is the only third party package I am using in the project, which btw is based on Umbraco v8.14.4 ☺

**Comment by abjerner** [comment]
I meant that some other package in my test setup might have added the key 🤔 not really sure...

**Comment by bjarnef** [comment]
Ahh. It could probably just use `buttons_save` or a custom key in the localization files in the plugin folder, since it already have various keys.

**Comment by abjerner** [comment]
The label key is also missing in my local test site, so not sure how I missed that. But I did cleanup a lot of the localization logic for the latest release, and the `general_add` key exists, so I probably didn't get around to testing the save button (or just didn't notice).

Anyways. I pushed a new commit using `buttons_save` 😉
