### ISSUE TITLE
v3: URLs with query parameters not forwarded

### ISSUE THREAD

**Issue by PhyxionNL** [skybrud/Skybrud.Umbraco.Redirects#104]
It's currently querying the database for a query parameter but forwarding isn't doing anything.

**Comment by abjerner** [comment]
Hi @PhyxionNL 

Is this still an issue with the latest alpha release?

You haven't provided a lot of information, so I'm closing the issue for now. If the issue still exist, and you can provide some more information, feel free to open the issue again 😉

**Comment by PhyxionNL** [comment]
I don't know, I have stopped using this and replaced it with rewrite rules.
