### ISSUE TITLE
Tillad ikke, at man vælge sites, som ligger i papirkurven

### ISSUE THREAD

**Issue by tnielsenskybruddk** [skybrud/Skybrud.Umbraco.Redirects#11]
På nuværende tidspunkt er det muligt at vælge et site, som ligger i papirkurven.

![2017-03-23 25](https://cloud.githubusercontent.com/assets/3634628/24244909/1878c220-0fc1-11e7-966d-48f0a0624e49.png)

**Comment by abjerner** [comment]
@tnielsenskybruddk this is now part of [v0.2.10](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v0.2.10) ;)
