### ISSUE TITLE
V9 Doesn't seem to trigger

### ISSUE THREAD

**Issue by AaronSadlerUK** [skybrud/Skybrud.Umbraco.Redirects#113]
I've installed the latest version into V9.0.1 and it doesn't seem to trigger on any redirects, I just get the normal 404 not found page.

Do I need to register something?

**Comment by abjerner** [comment]
Hi @AaronSadlerUK 

The latest version the time you created this issue would be `3.0.0-alpha005` - is this the version you're running?

The package had some problems if you either had set up an `Error404Collection` in Umbraco or added a custom content finder.

Does it work if you try upgrading to `v3.0.0-alpha006`? This release should address those issues. 

Btw - `v3.0.0-alpha007` is currently the latest release, so you might want to upgrade to that one instead.

Hope that helps 😉

**Comment by abjerner** [comment]
Hi @AaronSadlerUK 

As I haven't heard back from you, and I haven't been able to reproduce this issue, I'm closing the issue. Feel free to comment again if you have some more information 😉
