### ISSUE TITLE
Suggestion: support setting up HTTP 410 Gone responses

### ISSUE THREAD

**Issue by karlmacklin** [skybrud/Skybrud.Umbraco.Redirects#114]
Since this package lives in the realm of handling site migrations with redirect setups, I feel this is a useful addition.

When content intentionally is removed there can be a need to specifically reply with HTTP 410 to signal the content is gone and purposefully so. Search engines tend to respect this in a more direct fashion than a 404, which could actually be more of a site/setup error than intentionally deleted page.

**Comment by abjerner** [comment]
Hi @karlmacklin 

This would require a lot of restructuring of the package, so at least for now, it's outside the scope of this package.
