### ISSUE TITLE
Question: How to set dashboard permissions for specific user groups

### ISSUE THREAD

**Issue by alanwthom** [skybrud/Skybrud.Umbraco.Redirects#116]
Skybrud.Umbraco.Redirects: v2.0.7
UmbracoCms: v8.12.1

I'm looking to restrict access to the redirects dashboard to specific user groups (editor and admin). I've tried to do this via the `package.manifest` file in the App_Plugins folder as follows [based on the Umbraco docs](https://our.umbraco.com/Documentation/Extending/Dashboards/#specifying-permissions), but I think/suspect this may be overwritten by the [in-code configuration](https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/Dashboards/RedirectsDashboard.cs#L16)?

```
{
  "dashboards": [
    {
      "alias": "Skybrud.Umbraco.Redirects",
      "sections": [ "content" ],
      "view": "~/App_Plugins/Skybrud.Umbraco.Redirects/Views/Dashboard.html?v=2.0.7",
      "access": [
        { "deny": "writer" },
        { "grant": "editor" },
        { "grant": "admin" }
      ]
    }
  ]
}
````

I've also then tried to [override the dashboard](https://our.umbraco.com/Documentation/Extending/Dashboards/#override-an-umbraco-dashboard) to set specific access rules, but it appears that this isn't possible as I'm unable to reference the `RedirectDashboard` class as it's not included as content in the package? 

Any advice/help would be much appreciated. 

Thanks

**Comment by abjerner** [comment]
Hi @alanwthom 

The dashboard is controlled by the [**GetDashboardAccessRules** method](https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/Helpers/RedirectsBackOfficeHelper.cs#L29-L31) method in the `RedirectsBackOfficeHelper` class.

Although this example is for the Umbraco 9 package and for the content app, you can see an example here on how to replace the `RedirectsBackOfficeHelper` with your own implementation:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/120#issuecomment-1006653911

By overriding the `GetDashboardAccessRules` method, you can return your own array of `IAccessRule` indicating which groups should or shouldn't have access to the dashboard.

Hope that helps 😉

**Comment by alanwthom** [comment]
Hi @abjerner 

Many thanks for this. It looks like the v2.0.7 version that I had installed didn't have this helper, so I updated the version and was then able to override this. Thanks again for your help. 🙏
