### ISSUE TITLE
Permanent redirect has status 302 instead of 301

### ISSUE THREAD

**Issue by rubenberendsen** [skybrud/Skybrud.Umbraco.Redirects#117]
HI,

I have checked the package in Umbraco 9.1.2 with Redirects version 3.0.0-alpha006.

If i add a permanent redirect i except a 301 status code but it is a 302 status code

**Comment by abjerner** [comment]
Hi @rubenberendsen 

This is an oversight. Although the package is still in alpha for Umbraco 9, I'm not sure why I missed that. Should be fixed in [**v3.0.0-alpha007**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v3.0.0-alpha007) 😉 

Thanks for reporting 👍
