### ISSUE TITLE
[3.0.0-alpha007] Redirects with a root domain don't match

### ISSUE THREAD

**Issue by lauraneto** [skybrud/Skybrud.Umbraco.Redirects#118]
I've noticed that if I create a redirect and set a specific root domain (not all domains), the redirect won't work.
This is because when the middleware calls `GetRedirectByRequest` the Umbraco context has already been disposed.

I was thinking of doing a pull request for this, but looking at the current implementation I can see multiple possible solutions:
- Removing the need for the Umbraco context by using the `RootId` instead of the `RootKey` (not sure what's the reasoning between using one or the other and it seems that the `RootId` isn't being properly saved to the database)
- Using `IUmbracoContextFactory` to ensure we have an Umbraco context in `Response.OnStarting` and properly dispose it

What are your thoughts on this?
Also, this might be the cause of #113.

**Comment by abjerner** [comment]
Hi @lauraneto 

How are you hosting your Umbraco site?

I have a Umbraco 9.1.1 site which I've published via Visual Studio to IIS, and I can't reproduce the issue with `3.0.0-alpha007` 🤔

**Comment by abjerner** [comment]
@lauraneto have you found some time to have another look at this one?
