### ISSUE TITLE
[3.0.0-alpha007] Creating a new Folder takes user to Redirects tab with the message "This page has not been created yet. You must save and publish the page in order to be able to add redirects to it."

### ISSUE THREAD

**Issue by mrhodes-bd** [skybrud/Skybrud.Umbraco.Redirects#121]
When creating a new Folder in the content tree (i.e. a node that has list-view enabled), the user is shown the Redirects tab with the message "This page has not been created yet. You must save and publish the page in order to be able to add redirects to it." and is unable to name or save the node.

The workaround currently is to move to the Info tab, where it is then possible to give the node a name and Save and publish it.

Ideally, on folder creation, the user would be able to name and save the new node without needing to swap tabs first.

**Comment by abjerner** [comment]
Hi @mrhodes-bd 

The redirects package has a backoffice helper instance, and one of the things it's handling is the content app:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v3.0.0-alpha007/src/Skybrud.Umbraco.Redirects/Helpers/RedirectsBackOfficeHelper.cs#L194-L207

For content, `source` is an instance of `IContent`, which exposes a `ISimpleContentType` via the `ContentType` property. Unfortunately `ISimpleContentType` is rather limited, so I'm not not able to check whether the content type has any properties or whether it is a list view.

But as I described in the issue below, you can override the default implementation:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/120#issuecomment-1006653911

You can then check against specific content type IDs or aliases, and disable the content app accordingly. You can also look up the full `IContentTypeService`, also this might have a slight cost in performance.
