### ISSUE TITLE
404 error GetRedirectsForNode when viewing media node from inside media picker

### ISSUE THREAD

**Issue by TQ-Benji** [skybrud/Skybrud.Umbraco.Redirects#123]
Version 3.0.0-alpha007

Reproduce steps:
On a media picker property with an image set. 
Click the image to open the editor. 
Click Open in Media Library at the bottom,
Media library view opens but you get the 404 error appear at the bottom.

Seams like the request is setting the type parameter to content when it should be set to media
/umbraco/backoffice/Skybrud/Redirects/GetRedirectsForNode?key=91d3ab44-6bc6-4a7a-97e9-a08ba4591ec9&type=content

**Comment by abjerner** [comment]
@EM-Benji thanks for reporting 👍 

The type sent to the API *should* be based on the alias of the section. But with that being said, I'll have a look whether I messed something up in the code 😉

**Comment by abjerner** [comment]
Hi @EM-Benji 

This happened because basing the type on `$routeParams.section` when in infinite editing isn't reliable. This should be fixed now, and will be part of the next release 😉
