### ISSUE TITLE
Disable Angular dirty checking for the dashboard and property editor

### ISSUE THREAD

**Issue by abjerner** [skybrud/Skybrud.Umbraco.Redirects#13]
Angular and Umbraco will automatically do dirty checking (whether a field has an unsaved value) for dropdowns, input fields and similar since these are located within a form element. With the current dirty checking, user might see a notification like this (in Danish):

![image](https://cloud.githubusercontent.com/assets/3634580/24271927/5e2a4ec4-101b-11e7-90b2-1629465ae99c.png)

While the package itself handles saving and updating redirects, and some input fields are only used for filters, we really don't need Umbraco to handle dirty checking.

**Comment by skttl** [comment]
There is a directive in core that can be used. https://github.com/umbraco/Umbraco-CMS/blob/5397f2c53acbdeb0805e1fe39fda938f571d295a/src/Umbraco.Web.UI.Client/src/common/directives/validation/nodirtycheck.directive.js

Unfortunately it doesn't work on <select>s

**Comment by abjerner** [comment]
@skttl Thanks. I'm not sure I understand your last line, but yes, I've been using `no-dirty-check` in some of our other packages, but hadn't gotten around to add it here. At least until now - I've just pushed a new release ([v0.2.10](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v0.2.10)) that disables the relevant the dirty checking ;)

**Comment by skttl** [comment]
Ah, sorry :)

What I was trying to write, was that no-dirty-check doesn't work on select's. At least not for me :)

**Comment by abjerner** [comment]
No worries ;)

It worked fine for `select` from what I could tell. The `input` field was however a little tricky - it seems changing the order of the attributes may have something to say, as it worked by moving the `no-dirty-check` attribute a bit forward.

**Comment by skttl** [comment]
Cool :)

man. 28. aug. 2017 kl. 14.26 skrev Anders Bjerner <notifications@github.com
