### ISSUE TITLE
Multilingual issue

### ISSUE THREAD

**Issue by woodi123** [skybrud/Skybrud.Umbraco.Redirects#136]
I think there's an issue if you have a multilingual tree. Let's assume there are two cultures defined on the site:
- de-DE (default)
- fr-FR

I go to the backoffice and switch the tree to fr-FR. Then i create a content-redirect:

![image](https://user-images.githubusercontent.com/53077228/166235764-c6cf6fcb-fd29-416b-bb1e-aabafd55c77d.png)

As you see, the url seems correct but if i then open `/frtest` it takes me to the german version. Most probably becaue the url of the content item is just fetched with `.Url()` without culture parameter, so it takes the default culture.

Any ideas? 😊

**Comment by woodi123** [comment]
Hey @abjerner, any updates on this one? 🙂

**Comment by abjerner** [comment]
Hi @woodi123 

It's not something I currently have a good solution for.

For one, we're currently using Umbraco's link picker overlay for selecting the destination, which doesn't support selecting a culture. To support cultures, we'd either have to fully rewrite Umbraco's overlay or build something around it - both something that would take some time to implement.

People are also likely to have different opinions on how this should work, so there probably also goes some time into determining the correct approach.

**Comment by woodi123** [comment]
Hi @abjerner 

Thanks for the feedback. I see your points.\
Hoping, that you'll find a solution soon 😊

**Comment by abjerner** [comment]
@woodi123 I realize that this may no longer be relevant for you, but the U10+ package now supports culture specific redirects. 

Eg. in the example below, my about page varies by culture, so I'm now able to select whether the redirect should go English or the Danish version of the page.

![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/3634580/b1677e21-f48c-480b-9b50-8a0851f1caeb)
