### ISSUE TITLE
Add new redirect and Reload buttons are not visible in Umbraco 10

### ISSUE THREAD

**Issue by disarak** [skybrud/Skybrud.Umbraco.Redirects#144]
Hi 

After updating Umbraco 9 -> 10  I have installed Skybrud redirects but the "**Add new redirect**"  and "**Reload**" buttons are not visible on admin. Please see attached image. 

umbracoKeyValue is **3.0.0-alpha008** on database. Can someone please help? Thank you!

<img width="1848" alt="Skybrud" src="https://user-images.githubusercontent.com/15925693/176279533-4ea44f24-5114-4cfe-8c85-86e136036ccd.png">

**Comment by abjerner** [comment]
Hi @disarak 

Do I understand you correctly that you installed Skybrud Redirects *after* upgrading Umbraco?

What version of the package did you install? The entry in the `umbracoKeyValue` table only indicates the last migration to run, so the installed version doesn't necessarily match the package version. For Umbraco 10 you should be running v4.0.0.

Anyways - the UI hasn't loaded properly, so it's likely that a JavaScript error has occurred. Can you open the developer console and check if there are any errors?

How are you running the site? If in Visual Studio, have you tried cleaning right clicking on the solution, select **Clean solution**, and then try to rebuild? If you're using the console instead, you should be able to do something similar with `dotnet clean` and then `dotnet build`.

**Comment by disarak** [comment]
Yes @abjerner , it was an issue with UI. Apparently, JavaScript hasn't loaded properly.  All is working fine now.  Thank you for your support.

**Comment by parachute-dev** [comment]
@abjerner sorry to open this up again - but getting a very similar experience on Umbraco 10 and Skybrud. 

Works fine locally - publishing I get this error: would you know what I might be doing incorrectly?

umbraco-backoffice-js.js.v482ed8a50f640cfe7e0cedea2da6c1f11a5a80a3:147 Error: [$controller:ctrlreg] http://errors.angularjs.org/1.8.3/$controller/ctrlreg?p0=SkybrudUmbracoRedirects.Dashboard.Controller
    at umbraco-backoffice-js.js.v482ed8a50f640cfe7e0cedea2da6c1f11a5a80a3:25:168
    at umbraco-backoffice-js.js.v482ed8a50f640cfe7e0cedea2da6c1f11a5a80a3:117:19
    at ea (umbraco-backoffice-js.js.v482ed8a50f640cfe7e0cedea2da6c1f11a5a80a3:99:20)
    at p (umbraco-backoffice-js.js.v482ed8a50f640cfe7e0cedea2da6c1f11a5a80a3:90:355)
    at g (umbraco-backoffice-js.js.v482ed8a50f640cfe7e0cedea2da6c1f11a5a80a3:84:186)
    at umbraco-backoffice-js.js.v482ed8a50f640cfe7e0cedea2da6c1f11a5a80a3:83:311
    at Object.link (umbraco-backoffice-js.js.v482ed8a50f640cfe7e0cedea2da6c1f11a5a80a3:321:432)
    at umbraco-backoffice-js.js.v482ed8a50f640cfe7e0cedea2da6c1f11a5a80a3:35:134
    at Ca (umbraco-backoffice-js.js.v482ed8a50f640cfe7e0cedea2da6c1f11a5a80a3:108:361)
    at p (umbraco-backoffice-js.js.v482ed8a50f640cfe7e0cedea2da6c1f11a5a80a3:92:340) '<div ng-include="property.view">'

**Comment by abjerner** [comment]
@parachute-dev How are you doing a publish?

I think you're missing the actual error message, but from the "stack trace", it seems that the `SkybrudUmbracoRedirects.Dashboard.Controller` controller is missing. If this is the case, I'm guessing that all the backoffice assets from my package might be missing.

Can you check and confirm whether the published website has a `/App_Plugins/Skybrud.Umbraco.Redirects` folder?

Are there any other errors in the developer console? I guess if some JavaScript is loaded and fails before the `SkybrudUmbracoRedirects.Dashboard.Controller` controller is loaded, you could also see an error like that.

<hr />

Anyways - I've setting up a new project using the commands below, which works fine:

```
dotnet new -i Umbraco.Templates
dotnet new sln --name "RedirectsTests"
dotnet new umbraco -n "RedirectsTests"
dotnet sln add "RedirectsTests"
dotnet add "RedirectsTests" package Skybrud.Umbraco.Redirects
dotnet publish -o output
```

The last command with `dotnet publish` should ensure that the package's `.targets` file is executed. The `.targets` file is responsible for copying the backoffice assets to the output directory. In my case, the console output is something like this:

```
PS D:\Testing\Hello\RedirectsTests> dotnet publish -o output
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  RedirectsTests -> D:\Testing\Hello\RedirectsTests\bin\Debug\net6.0\RedirectsTests.dll
  Copying Umbraco json schema file
  Copying Skybrud.Umbraco.Redirects files: C:\Users\ander\.nuget\packages\skybrud.umbraco.redirects\4.0.0\build\..\cont
  ent\App_Plugins\Skybrud.Umbraco.Redirects\**\*.* - #29 files
  RedirectsTests -> D:\Testing\Hello\RedirectsTests\output\
```
