### ISSUE TITLE
Use radiobutton components

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#145]
It would be great if the redirects package used the `<umb-radiobutton>` component from Umbraco core at the advanced options - at least in the latest versions. I think the `<umb-radiobutton>` and `<umb-checkbox>`  components was initially included in Umbraco v8.0.0.

![image](https://user-images.githubusercontent.com/2919859/177147348-9542645d-d193-4794-8c45-df298f8e3176.png)

It would look more consistent with Umbraco core UI and Umbraco Forms also started using these components throughout since Umbraco Forms v8.7.0 as I recall.

![image](https://user-images.githubusercontent.com/2919859/177148213-2c297bb7-45bb-4946-9cd3-bdc614154d2c.png)

Alternatively a true/false setting like the "forward querystring" could use `<umb-toggle>`.

**Comment by abjerner** [comment]
@bjarnef this has being lying around inactive for way too long, so had a look at it. 

I'm not a fan of each radio button having it's own row, so I ended up with this:

![image](https://user-images.githubusercontent.com/3634580/189999482-b81040a2-ae80-4bb9-8926-dfc90b4f7992.png)

This is part of the new [`v4.0.3`](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v4.0.3) 😉
