### ISSUE TITLE
Doesn't work for 10.1.0.89

### ISSUE THREAD

**Issue by debwebdanmark** [skybrud/Skybrud.Umbraco.Redirects#148]
I have installed the nuget for Umbraco Cloud 10.1.0.89 and here it doesn't work.

It looks like this
![image](https://user-images.githubusercontent.com/2571686/188623906-5d4bf3e9-30d6-45c2-a9a5-41a72e02adaf.png)

It throws this in the console:
umbraco-backoffice-js.js.v637979751869315860:147 Error: [$compile:multidir] http://errors.angularjs.org/1.8.3/$compile/multidir?p0=redirectsNode&p1=%20(module%3A%20umbraco)&p2=redirectsNode&p3=%20(module%3A%20umbraco)&p4=template&p5=%3Credirects-node%20node%3D%22vm.node%22%3E
    at umbraco-backoffice-js.js.v637979751869315860:25:168
    at ba (umbraco-backoffice-js.js.v637979751869315860:103:448)
    at aa (umbraco-backoffice-js.js.v637979751869315860:96:378)
    at umbraco-backoffice-js.js.v637979751869315860:102:238
    at umbraco-backoffice-js.js.v637979751869315860:159:454
    at m.$digest (umbraco-backoffice-js.js.v637979751869315860:171:67)
    at m.$apply (umbraco-backoffice-js.js.v637979751869315860:174:484)
    at k (umbraco-backoffice-js.js.v637979751869315860:125:445)
    at v (umbraco-backoffice-js.js.v637979751869315860:131:40)
    at y.onload (umbraco-backoffice-js.js.v637979751869315860:131:464)
(anonymous) @ umbraco-backoffice-js.js.v637979751869315860:147

**Comment by abjerner** [comment]
Please include the what version of the package you've installed, and as many details as you can. Otherwise it's impossible for me to help you 😉

**Comment by debwebdanmark** [comment]
Hi @abjerner 
Installed the 4.0.1 to a Umbraco 10.1.0.89 .net 6 solution.

I simply installed the nuget package, build and tested it locally, and it looks like the picture above.

If I look under my debug folder under /App_plugins/Skybrud.Umbraco.Redirects there are only empty folders?

**Comment by abjerner** [comment]
I don't have a good idea what goes wrong then. As of 4.0.1, the package is a Razor Class Library, meaning you won't see any App_Plugins files when developing locally.

Are you sure all folders within `/App_plugins/Skybrud.Umbraco.Redirects` are in fact empty? And no `package.manifest` file?

Is this the first time you're installing the package in this solution, or did you upgrade from 4.0.0?

**Comment by abjerner** [comment]
@debwebdanmark are you able to provide any more information about this?

Anyways, I'm not entirely sure about the error message, but it may be because two Angular directives compete for the same name, and  thereby triggers an error. I haven't seen this with the redirects package before, and haven't heard others experiencing the same issue. But as an attempt to fix this issue, I've tried renaming the `redirectsNode` directive to `skybrudRedirectsNode`.

This is part of [`v4.0.2`](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v4.0.2) that I've just released. Can you try whether this fixes your issue?

**Comment by debwebdanmark** [comment]
hi @abjerner 
That fixed it 👍

**Comment by abjerner** [comment]
Awesome 😄 

I'm still not entirely sure why this happened. Maybe Umbraco has introduced a new directive specific to cloud, or maybe another package uses the same alias. Anyways, glad that it works now.
