### ISSUE TITLE
Redirects break when having any kind of 404 page.

### ISSUE THREAD

**Issue by royberris** [skybrud/Skybrud.Umbraco.Redirects#150]
When we set up redirects we are using 'All sites'. This adds a Guid.Empty to the database on the RootKey. In umbraco I have my domain set up as example.com. If I now browse to example.com/test which should be a redirect. I get the Umbraco 404 page. When I navigate to example.azurewebsites.net/test the redirect does work. Which is weird because the dashboard is labbeled as 'All sites'. But in truth it only matches if the domain is not in Umbraco.

Another issue is that if I now set the redirect to only work on the root note. The RootKey of the redirect is set to the key of the document node. But when I now go to example.com/test the redirect also does not work.

Whenever I go to a redirect from a domain configured in Umbraco the redirects do not seem to work. If I set my domain up as '/' in Umbraco. I can go to example.com/test if the redirect is set up for 'All Sites'.

Whenever a domain can be found, redirects do not work in our production environment. Whenever the domain is not in Umbraco, it works. It's was a hard issue to debug, but after hours of searching and looking at the source code I found this. 

Any idea what is going on here? We are using 3.0.4 with Umbraco 9.5.4.
We are hosting on Azure, but I can confirm this is not a Azure issue. When replicating this from my dev machine with different domains set up through the hostsfile, I get the same results as in Azure. 

--------

We ended up with a workaround. Where we redirect all traffic to the website to the www subdomain. And have the Umbraco domain configured without www. This way the redirects plugin will hit the Guid.Empty variant. And we can redirect the request. Because www.example.com is not in Umbraco's domain list, but example.com is.

**Comment by abjerner** [comment]
Hi @royberris 

You write that when you go to `example.com/test`, you'll see the Umbraco 404 page. What is the status code returned by this page?

For performance reasons, we don't really want the redirects module to intercept all requests, so the module the only kicks in when the server responds with a 404 status code. I'm suspecting the problem here is that the status is 200 OK or something else that 404.

**Comment by royberris** [comment]
Hi @abjerner 

Progressing more it might be the last chance content finder to present 404 pages that is interfering. But not sure why it only does that in scenarios where the domain is the same as set in Umbraco. How would I handle a 404 correctly while keeping this plugin to work

**Comment by abjerner** [comment]
What's your setup now? Is it a custom content finder? And even if the content finder shows the 404 page, it's important that the status code is 404 and not something else. If you can share some more about your setup, I can try to replicate it in my end.

**Comment by royberris** [comment]
@abjerner hi, problem was not with the package but with the content finder. The "fix" I described wasn't fixing the package, it was breaking the content finder. We tried to get the current domain with the Domain Service. But that doesn't work, when the domain in Umbraco is more than the HttpRequest Authority. So I had to fall back to another method trying to determine the content root based on the current request. Then I also had to set the status code to 404 in the `IPublishedRequestBuilder` and this seemed to fix the problem. Now I have a working content finder for the not found page, and I also have working redirects

**Comment by royberris** [comment]
Reopening this issue.

After thought of having it fixes (on development and acceptance) deploying it to production and it is broken again. I removed the content finder from the project, and reverted back to the way Umbraco describes it on the documentation. With a Error404Collection in the appsettings. This works, but guess what. If I set this the redirects stop working. 

```
"Error404Collection": [
  {
    "ContentKey": "76d2348e-52db-42da-aaca-d71da083d243",
    "Culture": "default"
  }
]
```

The moment I remove this from the appsettings, and reboot the Azure App Pool, the redirects work again.

Why can I not have a 404 page (served from Umbraco) with working redirects. Is there any known issue with the package? Or am I supposed to redirect to error pages differently?

**Comment by abjerner** [comment]
Hi @royberris 

Can you please reply back whether your 404 error page actually responds with a 404 status code? If it doesn't, this is the reason why the redirects module doesn't kick in.

I'm not aware of any existing issues. I've tried setting up a fresh 9.5.4 site, and install Skybrud Redirects 3.0.4, and then deploy the site to IIS. With a `Error404Collection` setup like in your last example, all three redirects work as intended:

![image](https://user-images.githubusercontent.com/3634580/189495820-4c42c0cb-e494-49ff-b303-8b39829f9d44.png)

**Comment by royberris** [comment]
Hi, after some more work on this we've found a different approach. We still haven't identified why one particular set-up causes this issue. Thanks for your time.
