### ISSUE TITLE
Issue on Umbraco 10

### ISSUE THREAD

**Issue by Global1337** [skybrud/Skybrud.Umbraco.Redirects#152]
Im using the new version 4.0.3 from Nuget.

Im having some sort of server issue. You can see my screenshots.
![image](https://user-images.githubusercontent.com/35682568/192764266-b7ca17ac-6c4d-4850-a3d4-f58d303cc301.png)

In the logs im getting the following: 
![image](https://user-images.githubusercontent.com/35682568/192764573-cef85374-8642-438f-b7de-dfd73ec3023a.png)

What to do? :D 

I've only had this problem with Umbraco 10(10.1.1 version).

**Comment by abjerner** [comment]
Hi @Global1337 

I'm not entirely sure how, but it could seem like one of the migrations of the package didn't run properly. Is it a fresh Umbraco installation, or was it upgraded from Umbraco 9 or something like that?

Can you check the following:

- Is there anything in the Umbraco logs? (specifically from when the package was installed)

- In the database, is there a row in the `umbracoKeyValue` table for `Umbraco.Core.Upgrader.State+Skybrud.Umbraco.Redirects`. If so, what is the value?

**Comment by Global1337** [comment]
@abjerner 

Its a fresh Umbraco 10 version.

The log: 
[skybrud-log.txt](https://github.com/skybrud/Skybrud.Umbraco.Redirects/files/9664933/skybrud-log.txt)


from the database: 
![image](https://user-images.githubusercontent.com/35682568/192779896-6418a38d-98c8-4033-a42b-e35cc1b37597.png)


Thanks a lot for the fast response time. :)

**Comment by abjerner** [comment]
Hi again. The log file appears to be after the package has been installed, so any errors from package's migrations are not in the log file.

I've tried to do some testing, but I haven't been able to reproduce the issue. For one, I've just tried to set up a new Umbraco 10.1 and with SQL Server, and the table in the database looks correct. I've also had no problems in the past with various version of Umbraco 10 and a mix of SQL Server and SQLite. What kind of database are you using?

If I understand you correctly, you haven't been able to create any redirects at all, so the `SkybrudRedirects` table would therefore be empty. If this is the case, you should be able to delete the `SkybrudRedirects` table, and delete the `Umbraco.Core.Upgrader.State+Skybrud.Umbraco.Redirects` row in the `umbracoKeyValue` table. When you restart your site, all the migrations should run again.

Let's see if that does the trick 😉

**Comment by Global1337** [comment]
> Hi again. The log file appears to be after the package has been installed, so any errors from package's migrations are not in the log file.
> 
> I've tried to do some testing, but I haven't been able to reproduce the issue. For one, I've just tried to set up a new Umbraco 10.1 and with SQL Server, and the table in the database looks correct. I've also had no problems in the past with various version of Umbraco 10 and a mix of SQL Server and SQLite. What kind of database are you using?
> 
> If I understand you correctly, you haven't been able to create any redirects at all, so the `SkybrudRedirects` table would therefore be empty. If this is the case, you should be able to delete the `SkybrudRedirects` table, and delete the `Umbraco.Core.Upgrader.State+Skybrud.Umbraco.Redirects` row in the `umbracoKeyValue` table. When you restart your site, all the migrations should run again.
> 
> Let's see if that does the trick 😉

It worked! :D 

Deleting the SkybrudRedirects table and the row in umbracoKeyValue did the job. 
Thanks a lot for the help
