### ISSUE TITLE
Editing a redirect sets the site property to All sites

### ISSUE THREAD

**Issue by sebastiandammark** [skybrud/Skybrud.Umbraco.Redirects#153]
When you edit an existing redirect the Site dropdown defaults back to *All sites*, and the end user probably doesn't notice this and hits save.
![image](https://user-images.githubusercontent.com/1575483/193573192-200cb9dc-ccd2-4865-a36b-c0bad42af11d.png)

This is an issue in Umbraco v9, and could also be an issue in Umbraco v10

**Comment by abjerner** [comment]
The issue has now been fixed as part of the new [`v4.0.4`](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v4.0.4) releases for Umbraco 10. 

The fix involved updating a single line, so if the Umbraco 9 package isn't all too different, it shouldn't take that long to fix for the Umbraco 9 package as well.
