### ISSUE TITLE
Outbound redirect doesn't resolve current URL for content and media destination

### ISSUE THREAD

**Issue by abjerner** [skybrud/Skybrud.Umbraco.Redirects#155]
If an outbound redirect is added to a page, and the destination is a content or media item within Umbraco, the URL of that item is stored along with it's `id` and `key`.

If the URL of the destination changes over time, it's still the URL of the time that the outbound redirect was created, that is returned.

Ideally the value converter should resolve the current URL of the content or media item, so it's always an up-to-date URL that is returned.

This affects both the Umbraco 9 and 10 versions of the package.

**Comment by abjerner** [comment]
This has now been fixed in [**v3.0.6**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v3.0.6) for Umbraco 9, and should be part of **v4.0.5** for Umbraco 10.

**Comment by miguelcrpinto** [comment]
is this a bug also on the Umbraco V8 version?

**Comment by abjerner** [comment]
@miguelcrpinto I can't remember for sure how it's implemented. Are you experiencing anything that might indicate that in the V8 as well?
