### ISSUE TITLE
Fresh install, adding a redirect fails with error in Danish

### ISSUE THREAD

**Issue by KirschnerMatt** [skybrud/Skybrud.Umbraco.Redirects#16]
Just installed this cool package. After following the setup guide, I attempted to add a redirect and received an untranslated error when attempting to submit:

Oprettelse fejlede: Grundet en fejl på serveren kunne dit redirect ikke oprettes.
Translation - Creation failed: Due to an error on the server, your redirect could not be created.

This is on my localhost and I couldn't find any more verbose errors in the Umbraco log nor Events Viewer, so I'm not sure what the issue is. I did notice that I'm unable to select any sites from the site dropdown, even though I have a single site setup. Are there any extra settings that I'm missing?

**Comment by KirschnerMatt** [comment]
Still having this issue, though I did figure out the Site dropdown options are determined by the Culture and Hostname setting on the root node. Even with my site properly declared, I get the same error message.

**Comment by abjerner** [comment]
@KirschnerMatt Thanks for reporting. I tested adding a new redirect, and can confirm this is an issue in 7.6.1, but not in 7.5.14. I will investigate further ;)

**Comment by abjerner** [comment]
Umbraco has apparently changed something for 7.6.x that affected the way the package was making calls to the database. I have adjusted the code a bit, and it now seems to work for 7.6.x as well. New release is here:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v0.2.8

Can you confirm that the new release is also working for you?

**Comment by KirschnerMatt** [comment]
That did the trick, though the success response was still in Danish rather than English. Is it perhaps due to this open issue? https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/8

My localization settings are set to en-US.

**Comment by abjerner** [comment]
Regarding the response, there are still some phrases throughout the package that are still hardcoded in either English or Danish. I haven't gotten around to fix this yet, but yes - it really should be fixed as well.

**Comment by KirschnerMatt** [comment]
Groovy, thanks for the update.

I like this package a lot, the Redirect property editor in particular is fantastic. Great job!
