### ISSUE TITLE
Problem redirecting pdf

### ISSUE THREAD

**Issue by marcusjm** [skybrud/Skybrud.Umbraco.Redirects#168]
Umbraco version 11.2.1
Skybrud Umbraco.Redirects 4.0.8

Regular pages work fine but while I get a 404 for my custom page it does not seem to see the pdf redirect for some reason.

![image](https://user-images.githubusercontent.com/20519880/226705234-7402ed2b-081a-4bda-8e1a-4aef82f6fac6.png)

**Comment by abjerner** [comment]
Hi @marcusjm 

So far I've been unable to reproduce that this shouldn't work. The requested URL is `/media/1417/msc-282-86-chap-v-reg-19.pdf`, right? What is the response status code?

Can you share what the redirect looks like in the database?

Do you have any configuration related to 404 handling? Both in `appsettings.json` or in either `Program.cs` or `Startup.cs`?

**Comment by marcusjm** [comment]
Only the one  regarding the custom page we discussed on discord. The response code this time is 404.

Removed the content due to being obsolete.

**Comment by marcusjm** [comment]
Ok that was the culprit then. Removal made it work.

**Comment by abjerner** [comment]
Great to hear it works. But to better understand the issue you had and what fixed it, what part did you remove?

The hotfix for settings the status code to 404 still seems to be required in 11.2.1, although that shouldn't affect static files.
