### ISSUE TITLE
Can't use Redirects with Error404Collection in AppSettings or IContentLastChanceFinder

### ISSUE THREAD

**Issue by dmiller21283** [skybrud/Skybrud.Umbraco.Redirects#171]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.8

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11

### Bug description

After implementing a 404 page using the recommended approach from Umbraco, all redirects end up on the 404 page. It seems that the 404 handler is running before the Redirect service. I've tried setting the status code in the request on my handler. I have also tried removing the last chance finder and using the Error404Collection in app settings. Both options run earlier in the request pipeline than the redirect service.

**Comment by abjerner** [comment]
What *exact* version of Umbraco are you on?

**Comment by dmiller21283** [comment]
I'm running Umbraco 11.2.2.

Reading through other issues, it looks like Redirects is dependent on a 404 status code. No matter what I did in the last chance handler, it always returns the 404 content page with a 200. I'm wondering if Umbraco changed something between major versions that changes the status code to a 200.

**Comment by abjerner** [comment]
Yes, Skybrud Redirects only kicks in for 404 requests.

Umbraco 11.2.x has a bug which causes 404 pages set up via `Error404Collection` to return 200. This was fixed in 11.3, so upgrading Umbraco should fix the issue.

**Comment by dmiller21283** [comment]
Upgraded to 11.3 and re-enabled my last chance finder and it's working again. Thanks for your help!
