### ISSUE TITLE
Cannot run in Linux

### ISSUE THREAD

**Issue by ccasalicchio** [skybrud/Skybrud.Umbraco.Redirects#173]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.8

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug description

When running on windows it works fine, but when I deploy it to a Ubuntu Server, the App_Plugins content stops working. How do I resolve this?
![image](https://user-images.githubusercontent.com/2466879/236868318-36330fa8-46f3-458c-9b2e-00912ef1b52b.png)
![image](https://user-images.githubusercontent.com/2466879/236868436-20fe9163-c621-4964-81fc-a80078ecd9d0.png)

**Comment by abjerner** [comment]
Hi @ccasalicchio 

What are your steps for deploying to the server?

If you're running a `dotnet publish` the output should have the `Skybrud.Umbraco.Redirects` folder in `App_Plugins`.

**Comment by ccasalicchio** [comment]
yes, that did it!, thank you!!!

**Comment by ccasalicchio** [comment]
Now I'm having a different issue.

Does the plugin allow to redirect to external sites?
![image](https://user-images.githubusercontent.com/2466879/236897977-84bba0ba-9525-43fc-9eff-75aa9dc2ee02.png)
![image](https://user-images.githubusercontent.com/2466879/236898746-da768483-f810-4748-9444-963bd8a35383.png)

**Comment by abjerner** [comment]
For the **Original URL** property, you shouldn't specify the the domain, so the warning above the field is correct. If you enter `/jobs` and pick **All sites** in the dropdown above, it will be a global redirect that works regardless of the domain. If you've added a domain to a node in the content tree, you'll be able to select the node in the dropdown, and then the redirect only applies to that domain (or domains if the node has multiple).

I haven't seen issues with the **Destination** property before. If you start over again, and specify the **Original URL** as described above, does it still occur?

**Comment by kmeilander** [comment]
We are using it on a Linux Azure App Service without any issues.  We are using version 4.0.14 on Umbraco v12.0.1. 

Everything has been working great for us.
