### ISSUE TITLE
Header disabled when creating new page

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#175]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.0

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.0.1

### Bug description

Our customer wanted to create a new category in a listview article, but noticed the header is disabled, which confused since the customer couldn't create and save the new node.

I noticed the document type doesn't have additional content properties, so the content app isn't shown, which otherwise it shown initially on node creation.

![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/2919859/890dea8f-8728-4b89-8a75-6277713ab90c)

However a workaround is to switch to info tab to create the node.

![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/2919859/e0d6b040-cd1e-4e41-8f8d-db3299626f1a)

Alternatively add some "dummy" properties to get the content app shown.

It seems to redirects content app doesn't show save / save & publish even the node is created, which may be fine.

It could eventually enhance this when new entity is created by checking `create=true` in querystring, e.g. mention to switch content app to create and save node.

**Comment by abjerner** [comment]
Hi @bjarnef 

`v4.0.0` is almost a year old. Have you tried updating?

Part of the issue happens when there are no properties, so no **Content** app shown before **Redirects**. Unfortunately Umbraco doesn't handle this too well.

Anyways, newer versions of the package will not show the content app if the page doesn't have a template. So in your case, the **Redirects** app shouldn't be shown with the newest version.

**Comment by bjarnef** [comment]
Hi @abjerner 
No, not yet :) 

Is v4.0.12 the latest for Umbraco 10?

I will try an upgrade to a newer version :)

**Comment by abjerner** [comment]
Yes. 4.0.12 is the newest version. It works for U10 and U11, and should in theory also work for U12.

**Comment by abjerner** [comment]
Btw - you can also control the content app a bit on your own - there is a bit of information for that here: https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/docs/v4/configuration/content-app.md

**Comment by bjarnef** [comment]
Cool :)

I upgrade to v4.0.12 and works a bit better for this specific project now.

**Comment by abjerner** [comment]
Closing this as the content app can be configured either through code or app settings.
