### ISSUE TITLE
Feature request - import CSV data

### ISSUE THREAD

**Issue by NISPico** [skybrud/Skybrud.Umbraco.Redirects#178]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.13

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0

### Question

Hello :)

I was wondering if you have any plans of adding an import feature, to import excel or csv, with a target and source.

I have quite a few redirects from an old site which i would like to be able to import.

**Comment by abjerner** [comment]
Hi @NISPico 

There is already an existing add-on for importing and exporting redirects. As it requires a few additional dependencies, it's released as a separator package.

- [**Skybrud Redirects Import**](https://github.com/skybrud/Skybrud.Umbraco.Redirects.Import)

It's still in alpha mode, but should be fine to use. I haven't implemented the JSON converter yet, but the CSV and XLSX imports should work just fine. You can read more about the column mapping [here](https://github.com/skybrud/Skybrud.Umbraco.Redirects.Import/blob/docs/v4/import/columns.md).

**Comment by abjerner** [comment]
Btw - there is also a smaller version available for Umbraco 7 so you can export a CSV file with all redirects from your Umbraco 7 site, and import them in your new site:

https://github.com/skybrud/Skybrud.Umbraco.Redirects.Import/tree/v1/main

**Comment by NISPico** [comment]
@abjerner Ahh, thank you, i already were using that package, but it was not compatible with Umbraco v12, but i see that you just updated it!

Thank you
