### ISSUE TITLE
Angular Error in v11 back office

### ISSUE THREAD

**Issue by snappercrumpleddog** [skybrud/Skybrud.Umbraco.Redirects#182]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.13

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug description

Hi,
I seem to be having a problem with the dashboard in the back office and I was wondering if this was a known thing?  When I go to the redirects dashboard, I get an angular error saying:
`angular.js:15697 TypeError: Cannot set properties of undefined (setting 'pagination')
    at Default.js?d=638276396000000000:149:38
    at angular.js:18075:37
    at m.$digest (angular.js:19242:15)
    at m.$apply (angular.js:19630:13)
    at angular.js:21773:25
    at Yg.completeTask (angular.js:21403:7)
    at angular.js:6879:7 'Possibly unhandled rejection: {}'`

And when I add a rule, I get this angular error:

`angular.js:15697 TypeError: Cannot read properties of undefined (reading 'limit')
    at vm.updateList (Default.js?d=638276396000000000:108:34)
    at Object.callback (Default.js?d=638276396000000000:53:20)
    at Object.submit (RedirectsService.js?d=638276396000000000:173:51)
    at Redirect.js?d=638276396000000000:486:30
    at angular.js:18075:37
    at m.$digest (angular.js:19242:15)
    at m.$apply (angular.js:19630:13)
    at k (angular.js:13473:36)
    at v (angular.js:13730:7)
    at y.onload (angular.js:13635:9) 'Possibly unhandled rejection: {}'`

And when the dashboard reloads, it looks like this:
![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/117160768/dcc1205b-5787-4d2d-beec-cda4f6678e1a)

Is this a bug or is there something I need to do to get the Angular behaving?

Many Thanks,
Simon

**Comment by abjerner** [comment]
Hi @snappercrumpleddog and thanks for reporting 👍 

It's not an issue I have seen before. Could you share what is returned by the `/umbraco/backoffice/Skybrud/Redirects/GetRedirects` endpoint? It's the general JSON structure that's important, so feel free to blank out sensitive information.

It could perhaps be something like https://github.com/skybrud/Skybrud.Umbraco.Redirects/pull/179 . I haven't had the time to look at this one yet as today is my first day back after about a month of vacation.

**Comment by abjerner** [comment]
I just had a quick look, and https://github.com/skybrud/Skybrud.Umbraco.Redirects/pull/179 doesn't seem to cause this, so the issue must be something else. Getting the output from the mentioned endpoint hopefully has some clues.

**Comment by snappercrumpleddog** [comment]
Hi Anders,
Thanks for coming back so quickly!
Here's the data from that endpoint, it's just test data so just the one rule at the moment, hope this helps!

`{"Pagination":{"total":1,"limit":20,"offset":0,"page":1,"pages":1,"from":1,"to":1},"items":[{"Id":10,"Key":"2d19f3fd-36fd-4517-898e-c39b720c5269","RootNode":null,"Path":"/sign-up","QueryString":"","Url":"/sign-up","Destination":{"Id":1164,"Key":"7393bfd4-4808-494c-8630-5149e19b1b78","Url":"/","Query":"","Fragment":"","DisplayUrl":"/","Name":"Home","Icon":"icon-home","Type":"content","IsNull":false,"IsTrashed":false,"IsPublished":true,"BackOfficeUrl":"/umbraco/#/content/content/edit/1296","Warning":null,"Culture":null,"CultureName":null},"CreateDate":"2023-08-14T19:56:06.103Z","UpdateDate":"2023-08-14T19:56:06.103Z","Type":"temporary","IsPermanent":false,"ForwardQueryString":false}]}`

**Comment by abjerner** [comment]
@snappercrumpleddog are you by any chance doing something to change the default settings for JSON serialization? The JSON properties are Pascal cased in your example, whereas default is regular camel cased.

**Comment by snappercrumpleddog** [comment]
@abjerner you're absolutely right, well spotted!  This project has some legacy code and the JSON serialization has been set to Pascal case and switching that back to camel case has got the dashboard working again.  Just need to figure out what the affect of that will be in the code!

**Comment by abjerner** [comment]
@snappercrumpleddog could you share your configuration to archive this? Are you using `System.Text.Json` or `Newtonsoft.Json`?

The issue reported in #179 is that property names are incorrect if replacing `System.Text.Json` with `Newtonsoft.Json`, but it seems that doing this the property names are still camel cased, albeit with incorrect property names due to missing property attributes to target `Newtonsoft.Json`. If you're using `Newtonsoft.Json`, it's possible that merging this PR will also fix the issue that you're reporting.

**Comment by snappercrumpleddog** [comment]
Sure, we using `.AddNewtonsoftJson( options => { options.UseMemberCasing(); });` in our startup.cs which looks very similar to #179.  Might be worth us giving that a go, is there a release it's been merged into yet?

**Comment by abjerner** [comment]
I hasn't been merged yet. I'm a little behind on things after coming back from vacation, but hopefully I'll be able to test and merge the PR and push a new release some time this week.

**Comment by abjerner** [comment]
Hi @snappercrumpleddog 

I did manage to find a bit of time, and I've now pushed a new [**v4.0.14**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v4.0.14) release that contains the fix from #179.

Can you confirm that this fixes your issue as well?

**Comment by snappercrumpleddog** [comment]
Morning @abjerner,

I've installed the new version and it all works!  Thanks for getting that version sorted out so quickly, much appreciated!
