### ISSUE TITLE
Internal Redirects Broken

### ISSUE THREAD

**Issue by Rhoyo** [skybrud/Skybrud.Umbraco.Redirects#183]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.8

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 10.4.2

### Bug description

As the title states, for my Umbraco Project, the internal redirects are not working. External works perfectly fine. 

I've read the documentation as well, and noted that having custom error pages could mess with the package. I route mine through a web.config in Azure to execute a URL. 

Turning off the custom error pages, the internal redirects still do not work to point to another internal page. Following along with the troubleshooting documentation. I checked to see that 404s were correctly returned on routing to a nonexistent page so it appears that 301 and 302 requests are not intercepted at least to my knowledge. My current idea is that it appears to be an environmental thing, however the internal redirects are broken both on my local and development environment.

I was thinking perhaps for development reasons internal redirects still work on dev and on live it is different. My live is currently broken so I am unable to see. If so is this an intended feature? Or are there perhaps other reasons why my internal redirects may not work. 

This same issue also appears in the older version I have of the project that also runs on a previous version, Umbraco 7.14.0. Using the package, although I am unable to determine which version of the package it is. It appears that the internal links on development do not work, however in the production environment for the older version of the project the internal redirects do work.

Thank you for your time and I would greatly appreciate your input.

**Comment by abjerner** [comment]
Hi @Rhoyo 

By _internal redirect_ , do you mean redirects to either content or media inside your Umbraco solution?

I can't think of a reason why only external redirects does work, but not internal redirects. Up until the point where the user is redirected, they should work exactly the same. It's however worth noticing that redirects will not work if another page exists at the original URL.

You write that you've looked for a 404 status code. Does this mean that if you visit the original URL of one of these redirects, you'll see a 404 status under **Network Tools** or what the equivalent is named in your browser?

**Comment by Rhoyo** [comment]
Hey @abjerner,

Sorry yes I mean to specify that I meant content redirects. On selecting a content redirect from the home directory it would not redirect from another content page.

I had seen previously about troubleshooting redirects with custom 404s enabled. I had it taken that on redirecting to my 404, if a 200 was returned instead of the correct response of 404 then the redirects would not work.


For example, you've noted that: 

"that redirects will not work if another page exists at the original URL."


I am understanding it like this, which does not work:

Original: Home/Stuff/Docs
Destination: Home/Stuff/

This does not work:

Original: Home/Stuff/
Destination: Home/Stuff/Docs

I am trying to make them work however, perhaps if I unpublish a page this might work.

Thank you for responding quickly, and inquiring further.
