### ISSUE TITLE
Dropdown menu actions hidden

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#186]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.16

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.1

### Bug description

In an Umbraco 12.1.1 project on Umbraco Cloud I have installed the following packages:

```
<PackageReference Include="Skybrud.Umbraco.Redirects" Version="4.0.16" />
<PackageReference Include="Skybrud.Umbraco.Redirects.Import" Version="4.0.0" />
```

However it seems the dropdown actions are cut-off.

![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/2919859/f0e3cb62-aaf1-4cff-870e-9bbe8925139d)

It seems to be because of the `overflow: auto` on `.umb-dashboard__content`:

![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/2919859/9ef5c2d4-8768-48c0-8fd6-e51013e28645)

**Comment by bjarnef** [comment]
Umbraco should probably add `flex: 1` to dashboard content to allow content area fit height.

![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/2919859/831d4fc4-027d-4508-b2d3-379d4259961e)

![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/2919859/1a7a4b82-15df-47e1-9640-32e71117b70a)

**Comment by abjerner** [comment]
Thanks @bjarnef 👍 

I've spotted this as well a few times, but I had forgotten about it as we're usually on Umbraco 10, where it isn't an issue.

I'll have a look at this 😉

**Comment by abjerner** [comment]
I was a bit too quick to reply, and thought this was a PR - if you have the time, you're more than welcome to submit a PR for this  👍

**Comment by bjarnef** [comment]
I fixed it 😄😅
https://github.com/umbraco/Umbraco-CMS/pull/14915

I think it need to be fixed in Umbraco core and shouldn't bee an issue when redirects table is shown. Only with little content and therefore the height is too small to show dropdown actions.

**Comment by abjerner** [comment]
Awesome 👍

**Comment by bjarnef** [comment]
@abjerner a workaround in redirects package is to set `min-height` on the container or the root div with class `skybrud-redirects-dashboard`.

![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/2919859/d767a07b-af5b-4af6-b495-4782ce38f294)

**Comment by abjerner** [comment]
Yes - I might do that. I recall also playing around with that before, so not sure why I didn't release that 🤔 

It's also only an issue when you have the import package installed as well, but would be nice to have a fix for that.
