### ISSUE TITLE
Double querystrings

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#189]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.17

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug description

I noticed when creating a URL with querystring and then edit it afterwards, the redirect has double querystring.

**Before**

```
/test?hello=world
```

![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/2919859/90caeb58-795d-49d3-bbed-462c746d4dea)

**After**

```
/test?hello=world?hello=world
```

![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/2919859/a0d610f3-ef1f-43e4-be06-099efe60de19)

**Comment by abjerner** [comment]
@bjarnef thanks for reporting 👍 

I can't remember if I changed something in the C# model. But now it's at least fixed for the U13 pre release.

I will look into cherry picking it back to V4 😉

**Comment by abjerner** [comment]
And now it's fixed in [**v4.0.18**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v4.0.18) as well 😎
