### ISSUE TITLE
Media files not re-directing

### ISSUE THREAD

**Issue by richard-arkom** [skybrud/Skybrud.Umbraco.Redirects#192]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.18

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug description

Re-directing media files does not seem to work,  is there any settings I need to check.

We are just trying to re-direct a jpg file to another jpg

Thanks
Rich

**Comment by abjerner** [comment]
Hi @richard-arkom 

Generally this should work without any issues.

Can you provide some more details about your setup? Do you have an example of the inbound URL? What happens when you access it? What is the status code returned by the server?

**Comment by richard-arkom** [comment]
Hi,

Apologies for the late reply, all works well, turns out the media item they wanted to redirect from was still in the recycle bin.

Thanks
