### ISSUE TITLE
Redirects based on the original URL query string

### ISSUE THREAD

**Issue by MiguelLopez6** [skybrud/Skybrud.Umbraco.Redirects#196]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.23

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.8.3

### Question

We have a set of URLs from the old website, where the old URL has an anchor and the new URL is a totally different page. 
For instance, we want to redirect from /industry-partners.html#hotel to /industry-partners/hotel-partners.
This is due to a restructure of the site. There are several pages that have been restructured and need to redirect to few different pages depending on the query string. 
When I add an original URL with the anchor, this is deleted automatically.
Is there a way to make it work? 
Thanks.

**Comment by abjerner** [comment]
Hi @MiguelLopez6 

Something like `#hotel` is not part of the query string, but the fragment part of the URL. This isn't passed on to the server, so the redirects package can't check against something like that.

I hope that makes sense 😉

**Comment by MiguelLopez6** [comment]
Thanks. I didn't mean "query string", but you understood me :).
Thanks for the clarification.
