### ISSUE TITLE
Is it possible for the campaign URL to remain visible in the address field instead of being replaced by the target URL?

### ISSUE THREAD

**Issue by sto-knowit** [skybrud/Skybrud.Umbraco.Redirects#202]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

13.0.4

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.0

### Question

Hi there

We are using this redirect package on a clients solution. They have asked if it would somehow be possible to have the url remain in the address field after redirect.

An example:
/campaignurl redirects to /this/is/an/example - but instead of having /this/is/an/example in the address field they would like to have the /campaignurl

Is it possible? Can the redirect method somehow be overwritten to do this?

Kind regards

STO

**Comment by abjerner** [comment]
Hi Sonni

This is not possible, and I don't think there is a straightforward way to accomplish this with the redirects package. Simply put, it's not what it is designed to handle.

You may be able to use ASP.NET Core's build-in rewrite logic instead, but then it wouldn't be a dynamic and not something that the editors can manage themselves.
