### ISSUE TITLE
Plans for Umbraco 14?

### ISSUE THREAD

**Issue by leddt** [skybrud/Skybrud.Umbraco.Redirects#207]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

N/A

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14+

### Question

Hi, we love your extension and are using it in multiple Umbraco 13 projects. We are currently planning a migration to Umbraco 14. 

Do you have plans to port this extension to Umbraco 14?

**Comment by andrewmac666** [comment]
Agree with this request! I'm currently running Umbraco 13.4.1, and have been using Skybrud.Redirects for the last few years - it's an extremely useful package, so an update to support Umbraco 14 would be awesome, please!

**Comment by abjerner** [comment]
I've somehow missed this issue, so sorry for the lack of reply. I've already been working a bit on upgrading the package for Umbraco 14, and I've just pushed the first alpha release:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v14.0.0-alpha001

For now, I've implemented the redirects middleware as well as the redirects dashboard. These should work similar to how they worked in previous versions of the package. I can't say for sure that they are 100% done, so feel free to create a new issue if you spot something that doesn't look finished.

Previous versions of the package also included a content app, a property editor for managing inbound redirects (as an alternative to the content app) and a property editor for managing an outbound redirect. I haven't looked into these yet, but the plan is that these should also be available in the Umbraco 14 package. I just don't know yet when I'll be able to work on those.

**Comment by leddt** [comment]
Nice! We'll likely test it in the coming weeks.
Thanks for your work!

**Comment by abjerner** [comment]
I've also just created a new issue to track the progress for upgrading the package for Umbraco 14: https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/208

**Comment by andrewmac666** [comment]
Fantastic, thank you so much Anders - hugely appreciated!
