### ISSUE TITLE
Site-specific redirects for static files not working

### ISSUE THREAD

**Issue by tomvanenckevort-ez** [skybrud/Skybrud.Umbraco.Redirects#22]
When you try to add a redirect for a static file, for example from `http://www.mysite.com/old.pdf` to `http://www.mysite.com/my-new-page`, it will not work when you select a specific site from the dropdown.

Since it will go through the HttpModule without an Umbraco context it will fail to get the domain assigned for the current request, and it will default to get the redirects which are set to 'All sites' (ID = 0).
So the example redirect mentioned above does work when I set it to 'All sites', but not when I select the specific site from the dropdown.

I noticed a comment in the code that mentioned a TODO item to add code which retrieves the domain using the DomainService. I've now added this in and created a pull request for this.

Adding in this piece of code will mean the correct `IDomain` object is retrieved for the current request, and the site-specific redirect will now execute as expected.

**Comment by abjerner** [comment]
Thanks for the issue and pull request. I haven't had the time to look into it after coming back from vacation, but I'll hopefully have some time soon ;)

**Comment by martijn1k** [comment]
Excellent Tom! I have the same issue when migrating a site, .html, .pdf etc. redirects are not working.
Thanks for figuring out a work-arround, much appreciated.

**Comment by tomvanenckevort-ez** [comment]
@abjerner Sorry to hassle you, but did you get a chance yet to review the PR?

**Comment by abjerner** [comment]
@tomvanenckevort-ez Not yet, unfortunately. I'm still working on merging one of the previous pull requests. I don't know yet when I'll be able to merge this pull request :(

**Comment by abjerner** [comment]
Should've done this many months ago (again **#H5IS**), but I've now merged the pull request from @tomvanenckevort-ez and pushed a new release: https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v0.3.4

Thanks for the effort 👍

**Comment by tomvanenckevort-ez** [comment]
Awesome! Thanks for merging and releasing a new version.

**Comment by marcusjm** [comment]
Seems this issue has re-emerged with Umbraco 10/11. It works with regular pages but not pdf apparently.

![image](https://user-images.githubusercontent.com/20519880/226691128-87a79261-eff0-4c25-b532-120476d0ef85.png)
