### ISSUE TITLE
Manual URL entry edit broken

### ISSUE THREAD

**Issue by martijn1k** [skybrud/Skybrud.Umbraco.Redirects#25]
After inserting a static redirect entry, editing it afterwards will result in an empty Original URL field.
Both the Original URL and the Destination are shown in the list. Searching for the original url works, 
and the redirect works.

Adding for example:
Original URL: /some-path/some-page/
Destination: https://www.site.com/new-page/

When editing the entry the Desination is still filled in though, 
just the Original field is empty.

**Comment by abjerner** [comment]
@martijn1k Thanks for reporting 👍

Can you describe your steps a bit further? I've tried setting up a fresh Umbraco 7.6.5 installation with Skybrud.Umbraco.Redirects 0.2.10, and I haven't been able to reproduce the issue you're describing.

**Comment by abjerner** [comment]
@martijn1k Anything new for this one?
