### ISSUE TITLE
Change $scope to vm

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#28]
I wonder if we should replace `$scope` by `var this = vm;` as discussed on our here and follow the Angular best practice guide as Kevin link to in the forum thread:
https://our.umbraco.org/forum/developing-packages/88025-this-vs-scope-in-angularjs-controllers

and I have noticed Umbraco HQ use it more frequent in core.

**Comment by abjerner** [comment]
Maybe. If using $scope doesn't cause any issues, changing the controller to an isolated scope won't have  that high a priority.

**Comment by bjarnef** [comment]
It is maybe a matter of code style, but also if referring to `$parent` it seems to be better to use `controllerAs` syntax. But it is not that important though.

**Comment by abjerner** [comment]
I agree regarding the code style. I've marked the issue as **Could have**, so I'll come back to it later. But for now, there are more important issues and pull requests across our packages ;)

**Comment by abjerner** [comment]
@bjarnef better late than never, the redirects package will be using `vm` from the next release 👍
