### ISSUE TITLE
.aspx bliver sorteret fra

### ISSUE THREAD

**Issue by tnielsenskybruddk** [skybrud/Skybrud.Umbraco.Redirects#3]
På danishcrown.dk oplever vi, at .aspx bliver sorteret fra, når man opretter et nyt redirect (som indeholder .aspx). Pt. løser vi problemet ved at tilføje det manuelt i databasen efterfølgende.

**Comment by abjerner** [comment]
@tnielsenskybruddk Jeg kan ikke genskabe denne, så måske er det blevet rettet/ændret i Umbraco (da vi egentlig blot bruger deres linkpicker-dialog).

**Comment by abjerner** [comment]
@tnielsenskybruddk Kan du hjælpe med at teste om denne stadig er et issue, eller om den bare skal lukkes?

**Comment by abjerner** [comment]
Åbenbart ikke 😒
