### ISSUE TITLE
Failed to install on Umbraco Cloud v7.8.1

### ISSUE THREAD

**Issue by greystate** [skybrud/Skybrud.Umbraco.Redirects#33]
Just installed the package in a v7.8.1 on Umbraco Cloud but I'm getting what I assume is a DLL version and or reference error:

> Could not load file or assembly 'Skybrud.Umbraco.Redirects' or one of its dependencies. The system cannot find the file specified.

The DLL is in the bin folder, so I'm suspecting it can't load one of its dependencies (as it says).

**Comment by abjerner** [comment]
@greystate Thanks for reporting. I'm not really familiar with Cloud, so I'm not sure what would cause this.

Do you have any other Skybrud DLLs in your bin folder? And if so, what are their versions?

**Comment by abjerner** [comment]
Oh, and does the same code work locally?

**Comment by greystate** [comment]
Happy to report I was too fast :-)

"locally"??? I'm on a Mac - we don't do Umbraco locally :-)

Turns out the DLLs were actually *not* in the bin folder, as they're ignored by the .gitignore file - had to   force-add them before pushing everything up.

It works now! (Or at least I'm seeing the dashboard - will report further if it doesn't actually work :-)

Thanks!!
