### ISSUE TITLE
No pane appears

### ISSUE THREAD

**Issue by Ladefuss** [skybrud/Skybrud.Umbraco.Redirects#35]
Thanks for creating this great package, Anders.

- Installed latest via Nuget (0.3.4) on umbraco 7.5.13. 
- Everything installs and builds. 
- I made the required changes to web.config and dashboard.config

Still no "Redirects" pane appears in backoffice.

- No errors in console or log.
- I tried different browser and editing clientdependencies.config to rule out client caching

Have i missed anything? Is Umbraco 7.5.13 ok with v. 0.3.4?

Have a great day

**Comment by abjerner** [comment]
@Ladefuss What kind of user are you in the backoffice? The example for adding the dashboard is limited to admins, and therefore won't be shown for editors etc. You can remove the `<access>` element, and it should be shown to all user types ;)

If it still doesn't work, would it be possible for you to share your `/config/Dashboard.config` file?

**Comment by Ladefuss** [comment]
I am logged in as admin. I removed the <access> node exactly to test if the problem was permission-based but it wasn't.

<?xml version="1.0" encoding="utf-8"?>
<dashBoard>
  <section alias="StartupSettingsDashboardSection">
    <areas>
      <area>settings</area>
    </areas>
    <tab caption="Welcome">
      <control showOnce="true" addPanel="true" panelCaption="">
        views/dashboard/settings/settingsdashboardintro.html
      </control>
    </tab>
  </section>
  <section alias="StartupDeveloperDashboardSection">
    <areas>
      <area>developer</area>
    </areas>
    <tab caption="Get Started">
      <control showOnce="true" addPanel="true" panelCaption="">
        views/dashboard/developer/developerdashboardvideos.html
      </control>
    </tab>
    <tab caption="Examine Management">
      <control>
        views/dashboard/developer/examinemanagement.html
      </control>
    </tab>
  </section>
  <section alias="StartupMediaDashboardSection">
    <areas>
      <area>media</area>
    </areas>
    <tab caption="Content">
      <control showOnce="false" addPanel="false" panelCaption="">
        views/dashboard/media/mediafolderbrowser.html
      </control>
    </tab>
  </section>
  <section alias="StartupDashboardSection">
    <access>
      <deny>translator</deny>
    </access>
    <areas>
      <area>content</area>
    </areas>
    <tab caption="Get Started">
      <access>
        <grant>admin</grant>
      </access>
      <control showOnce="true" addPanel="true" panelCaption="">
        views/dashboard/default/startupdashboardintro.html
      </control>
    </tab>
  </section>
  <section alias="StartupMemberDashboardSection">
    <areas>
      <area>member</area>
    </areas>
    <tab caption="Get Started">
      <control showOnce="true" addPanel="true" panelCaption="">
        views/dashboard/members/membersdashboardvideos.html
      </control>
    </tab>
  </section>
  <section alias="UmbracoModelsBuilder">
    <areas>
      <area>developer</area>
    </areas>
    <tab caption="Models Builder">
      <control>
        /App_Plugins/ModelsBuilder/modelsbuilder.htm
      </control>
    </tab>
  </section>
  <section alias="UmbracoHealthCheck">
    <areas>
      <area>developer</area>
    </areas>
    <tab caption="Health Check">
      <control>
        views/dashboard/developer/healthcheck.html
      </control>
    </tab>
  </section>
  <section alias="RedirectUrlManagement">
    <areas>
      <area>content</area>
    </areas>
    <tab caption="Redirect URL Management">
      <control>
        views/dashboard/developer/redirecturls.html
      </control>
    </tab>
  </section>
  <section alias="StartupFormsDashboardSection">
    <areas>
      <area>forms</area>
    </areas>
    <tab caption="Dashboard">
      <control>/app_plugins/umbracoforms/backoffice/dashboards/licensing.html</control>
      <control>/app_plugins/umbracoforms/backoffice/dashboards/yourforms.html</control>
      <control>/app_plugins/umbracoforms/backoffice/dashboards/activity.html</control>
    </tab>
    <tab caption="Redirects">
      <control showOnce="true" addPanel="true" panelCaption="">/App_Plugins/Skybrud.Umbraco.Redirects/Views/Dashboard.html</control>
    </tab>
  </section>
</dashBoard>

**Comment by Ladefuss** [comment]
Wait. I think i found my error. Don't waste more time for now :)

**Comment by abjerner** [comment]
Forms? 😄

**Comment by Ladefuss** [comment]
Exactly :) Thanks again Anders. I will try not to waste more of your time from now on :) 

Have a great day in Vejle :) Oh and give my regards to Thomas and Torben :) 
They might remember my name back from the early days at Aakjaers :)

**Comment by abjerner** [comment]
No worries ;)

Thomas is sitting just opposite me at the office, so I've forwarded your regards.
