### ISSUE TITLE
Adding redirect to new media URL still saves old URL

### ISSUE THREAD

**Issue by ronaldbarendse** [skybrud/Skybrud.Umbraco.Redirects#36]
Having good image URLs/file names helps with SEO, so an editor is re-uploading images with better filenames from the Umbraco back-office (to the same media entity - I haven't found another built-in way to do this).

Instead of having the editor also manually add the redirect (with query string forwarding on, so ImageProcessor options are preserved), I created an event handler to do this:

```c#
protected void MediaService_Saving(IMediaService sender, SaveEventArgs<IMedia> e)
{
	var renamedMedia = e.SavedEntities.Where(m => !m.IsNewEntity() && m.IsPropertyDirty(Constants.Conventions.Media.File)).ToList();
	if (renamedMedia.Count > 0)
	{
		var repository = new RedirectsRepository();
		var logger = ApplicationContext.Current.ProfilingLogger.Logger;

		foreach (var media in renamedMedia)
		{
			try
			{
				var cachedMedia = UmbracoContext.Current.MediaCache.GetById(media.Id);
				var url = media.GetUrl(Constants.Conventions.Media.File, logger);

				// Save new redirect
				var redirect = repository.AddRedirect(0, cachedMedia.Url, new RedirectLinkItem(media.Id, media.Name, url, RedirectLinkMode.Media), true, false, true);
				logger.Info(this.GetType(), "Redirect automatically added for media {0} from {1} to {2}", () => media.Id, () => redirect.Url, () => redirect.LinkUrl);
			}
			catch (RedirectsException ex)
			{
				logger.WarnWithException(this.GetType(), "Redirect could not be automatically added for media {0}", ex, () => media.Id);
			}
		}
	}
}
```

**Instead of saving the `url` passed to `RedirectLinkItem`, the media URL is saved... This also causes a redirect loop, since the source and destination URLs are the same and the redirect module also doesn't use the new URL when doing the redirect.**

Setting the id to 0 and the `RedirectLinkMode` to `Url` fixes this, but you loose the ability to lookup redirects for that media item.

**Comment by abjerner** [comment]
@ronaldbarendse I think this is a bit of en edge case, but it is actually already supported.

If you change:

```csharp
var redirect = repository.AddRedirect(0, cachedMedia.Url, new RedirectLinkItem(media.Id, media.Name, url, RedirectLinkMode.Media), true, false, true);
```

to

```csharp
var redirect = repository.AddRedirect(0, cachedMedia.Url, new RedirectLinkItem(media.Id, media.Name, url, url, RedirectLinkMode.Media), true, false, true);
```

it should work. The second `url` is a raw URL that isn't automatically replaced ;)

**Comment by ronaldbarendse** [comment]
@abjerner I missed that overload, now it does indeed save the correct URL and shows the redirect is linked to media! 😄

The other issue still remains: the redirect module doesn't seem to use the most recent URL for content and media. So if you change `/media/1000/example.jpg` to `/media/1000/example-2.jpg` and then to `/media/1000/example-3.jpg`, you get 2 redirects when requesting `/media/1000/example.jpg`... This seems redundant, because it's linked to media and can retrieve the correct URL on the first request.

**Comment by ronaldbarendse** [comment]
Let's track my previous comment about using the outdated, saved URL instead of the current content/media URL in https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/63#issuecomment-627409023, as it also needs a rewrite to support culture variant content URLs.
