### ISSUE TITLE
Redirect from default.aspx doesn't work

### ISSUE THREAD

**Issue by villian** [skybrud/Skybrud.Umbraco.Redirects#37]
Redirect from default.aspx to any other url doesn't work

**Comment by villian** [comment]
hi, @abjerner , yes in the root

**Comment by abjerner** [comment]
@villian While I still think of possible solutions, could you perhaps describe your use case a bit more? The more details the better ;)

Some redirects are better handled using IIS rewrites, which may be the case with `/default.aspx`.
