### ISSUE TITLE
Zip file is missing a dependent dll: Skybrud.WebApi.Json

### ISSUE THREAD

**Issue by protherj** [skybrud/Skybrud.Umbraco.Redirects#4]
If I download the zip file from the Releases on Github, then copy the files into a new download of Umbraco I get an error page on load:

Server Error in '/' Application.

Could not load file or assembly 'Skybrud.WebApi.Json, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

This is a bit of a pain because the releases of 'Skybrud.WebApi.Json' doesn't have a zip download so I have to download the source and build it to get the dll.

Generally, I'd use nuget to pull all this in, but I'm just doing some quick testing.

**Comment by abjerner** [comment]
Sorry about that. The DLL should obviously be in the ZIP release as well - I'll look into that tomorrow.

Thanks for reporting ;)

**Comment by abjerner** [comment]
I have now released [v0.2.3](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v0.2.3), where the ZIP now contains the required DLLs ;)

Although now included in the release mentioned above, the DLL of `Skybrud.WebApi.Json` is now also available for download here: https://github.com/abjerner/Skybrud.WebApi.Json/releases
