### ISSUE TITLE
Adding redirect for urls including index.php

### ISSUE THREAD

**Issue by ruant** [skybrud/Skybrud.Umbraco.Redirects#45]
I've moved an old Joomla site over to Umbraco.
And I'm trying to do some redirects.
When I try to enter `https://domain.com/index.php/contact-us` I get and error saying:  
`The specified URL is not valid. A valid URL should look like /page or /page/subpage.`  

If I go to any of these old index.php URL's I do get a 404 response back.

Any tricks to make this work?

**Comment by ruant** [comment]
Ok. Sorry for that.
I'm just a retard.. The https://domain.com part should be included 🤦‍♂

**Comment by abjerner** [comment]
@ruant Good to see you found out. But one could argue that the UI could explain this a bit better 😉

**Comment by ruant** [comment]
Perhaps, or people will find this issue and have the same AHA-moment as I had 😆

**Comment by ruant** [comment]
I'll make a PR to change the text

**Comment by ruant** [comment]
https://github.com/skybrud/Skybrud.Umbraco.Redirects/pull/46
