### ISSUE TITLE
GetRedirectsByUrl always returns all ForwardQueryString=true redirects

### ISSUE THREAD

**Issue by ronaldbarendse** [skybrud/Skybrud.Umbraco.Redirects#49]
It looks like the 'Forward query string' is broken in another way (besides not correctly redirecting: https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/43), as `GetRedirectsByUrl` returns all redirects with `ForwardQueryString=true`:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/7f8680784de6808fa60eb707e2c1385d5e18a22d/src/Skybrud.Umbraco.Redirects/Models/RedirectsService.cs#L403

**Comment by abjerner** [comment]
@ronaldbarendse sorry for the waiting time. Vacation and generally being busy happened, so this took a bit longer than it should have.

New release with a fix is here: https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v0.3.5

The same issue exists in the releases for Umbraco 8, so I'll leave the issue open until I can push a new release for Umbraco 8 as well.

**Comment by abjerner** [comment]
The bug is now fixed for Umbraco 8 as well (but not yet released).
