### ISSUE TITLE
Not possible to add a redirect with a "manual" destination in Umbraco 8

### ISSUE THREAD

**Issue by mastrup** [skybrud/Skybrud.Umbraco.Redirects#51]
When typing in a destination URL, and not picking one from the tree, the adding of a new redirect fails: https://streamable.com/ops87

I have been trying to do the same in Umbraco 7, with no issues: https://streamable.com/zmj2b

**Comment by abjerner** [comment]
Hi @mastrup and thanks for reporting 👍 

I haven't come across this when testing, but I will investigate.

Anyways, since the notification means an error happened on the server, is there anything useful in the Umbraco log file?

**Comment by mastrup** [comment]
Forgot to include the log! 🙄
Here you go: https://pastebin.com/XNdCLfhJ

**Comment by AndersBrohus-MySupport** [comment]
I'm having the same issue :)

**Comment by abjerner** [comment]
This was a silly mistake that I should have caught while testing - but then again, there was a reason this was released as an alpha 😄 

I pushed a new alpha release that fixes this: https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v2.0.0-alpha003
