### ISSUE TITLE
Can't create site specific redirects

### ISSUE THREAD

**Issue by AndersBrohus-MySupport** [skybrud/Skybrud.Umbraco.Redirects#52]
Hi Anders :)

In the alpha for V8 i can't create site specific redirects.. :)
It's simply not an option, like in the v7 package :)

**Comment by abjerner** [comment]
Hi Anders,

This is of course something that will be back, but I haven't had the time to implement it yet. Hopefully this will be available soon 😉

**Comment by abjerner** [comment]
Hi @AndersBrohus-MySupport,

This is now supported in the latest release: https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v2.0.1

**Comment by AndersBrohus-MySupport** [comment]
Hi @abjerner 

Thanks alot! :)
