### ISSUE TITLE
Javascript error when using inbound redirect property editor in back office

### ISSUE THREAD

**Issue by amitch17** [skybrud/Skybrud.Umbraco.Redirects#54]
Hi, this is using the alpha004 release, on Umbraco 8.1.4

Simple functionality from the dashboard seems to work fine.  Thank you for this project.

Bug:

- I added the Inbound redirect property editor to a composition I am using on all my pages and saved.
- Go into Content and open that page.
- The property editor does not appear, following javascript error in console:

![image](https://user-images.githubusercontent.com/18399155/64356342-9def7380-cffa-11e9-8371-46fa31cddfdf.png)

`angular.js?cdv=1194169033:15536 Error: [$injector:unpr] Unknown provider: dialogServiceProvider <- dialogService <- SkybrudUmbracoRedirects.PropertyEditor.Controller
https://errors.angularjs.org/1.7.5/$injector/unpr?p0=dialogServiceProvider%20%3C-%20dialogService%20%3C-%20SkybrudUmbracoRedirects.PropertyEditor.Controller
    at angular.js?cdv=1194169033:138
    at angular.js?cdv=1194169033:4905
    at Object.getService [as get] (angular.js?cdv=1194169033:5065)
    at angular.js?cdv=1194169033:4910
    at getService (angular.js?cdv=1194169033:5065)
    at injectionArgs (angular.js?cdv=1194169033:5090)
    at Object.invoke (angular.js?cdv=1194169033:5114)
    at $controllerInit (angular.js?cdv=1194169033:11673)
    at nodeLinkFn (angular.js?cdv=1194169033:10486)
    at compositeLinkFn (angular.js?cdv=1194169033:9801) "<div ng-include="propertyEditorView" class="ng-scope">"`

**Comment by abjerner** [comment]
Hi @amitch17 and thanks for reporting,

The property editor has not been updated for V8 yet, so the error is because it's still relying on `dialogServiceProvider`from V7, which isn't available in V8.

It's already on my TODO list, but I haven't gotten around to updating it yet.

**Comment by abjerner** [comment]
@amitch17 sorry for not getting back to you on this. You created this issue when the package was still only available as an alpha release, so it was fixed before we've released the first stable release.
