### ISSUE TITLE
Unable to add redirects to media types File and Image in umbraco 8.1.2

### ISSUE THREAD

**Issue by John-Blair** [skybrud/Skybrud.Umbraco.Redirects#56]
When I add the property editor "Skybrud Redirect - Inbound redirects" to Media Type file and Image in Umbraco 8.1.2 - the property editor does not show up when items of these types are added.

The content dashboard "Redirects" does show up and I can manually enter media file redirects there. e.g. /catalog will redirect to /media/l2hpnd4k/catalog.pdf

**Comment by abjerner** [comment]
Hi @John-Blair,

I haven't had the time to update the property editor yet. It's still based on the code for Umbraco 7, and therefore fails when you try to use it in Umbraco 8. Hopefully I'll be able to look at this soon ;)

**Comment by abjerner** [comment]
@John-Blair sorry for not getting back to you on this. The problem that you're describing seems like something that fixed a while ago. 

If you're still having problems with this, could you test and confirm whether this is still an issue in the latest version of the Umbraco 8 package?

I'm closing the issue for now, but we can open it again if the issue still exist.
