### ISSUE TITLE
v2.0.0 is missing declared dependency on Umbraco 8 in NuGet package

### ISSUE THREAD

**Issue by lcichanowicz** [skybrud/Skybrud.Umbraco.Redirects#57]
I just installed Skybrud.Umbraco.Redirects 2.0.0 via NuGet Package Manager (GUI) in Visual Studio 2019, on an Umbraco 7.15.3 project.  Now, I get a YSOD:

_Could not load file or assembly 'Umbraco.Web, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified._

After simply uninstalling Skybrud.Umbraco.Redirects 2.0.0 via NuGet Package Manager, Umbraco runs fine.

**Comment by abjerner** [comment]
Hi @lcichanowicz,

Version 2 only works for Umbraco 8, which is why your solution fails when installing the package in Umbraco 7.

For Umbraco 7, you can install the older `v0.3.5`:

```
Install-Package Skybrud.Umbraco.Redirects -Version 0.3.5
```

I've tried to document this in both the [release notes](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases) and on NuGet. If you have ideas to make this more clear, I'd be happy to have another look ;)

**Comment by lcichanowicz** [comment]
Hi, @abjerner.  You can inform the NuGet package of the dependency on Umbraco 8.  This will prevent it from installing on lower versions, with a friendly message.

https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#semantic-versioning-200

**Comment by abjerner** [comment]
Thanks - I will look into that. But wouldn't Visual Studio do a force update the Umbraco dependency instead of asking what to do? That is at least my experience, and one of the reasons I'm only using Umbraco as a development dependency.

**Comment by lcichanowicz** [comment]
Oh, yes, actually that is correct; however, it at least shows the dependency before installation, in the places where I am accustomed to looking for it: the package description's Dependencies section, and the modal showing what components are about to be installed.

To ensure I do not inadvertently take such a dependent update--again--I have leveraged this solution in my Umbraco projects.
https://stackoverflow.com/a/22563668/3537393

![image](https://user-images.githubusercontent.com/4871064/65724433-60708a00-e07e-11e9-9811-f4206d9ba2c9.png)
...From here: https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#semantic-versioning-200

![image](https://user-images.githubusercontent.com/4871064/65724349-2d2dfb00-e07e-11e9-8c71-9167cd6b6a7e.png)

This has the added benefit of not showing available updates that would require going to Umbraco 8.

**Comment by lcichanowicz** [comment]
Greetings, @abjerner.  I just set up a new Umbraco 7.15.3 site and I see the dependency is still missing.  Based on the title of my issue, I'd say this should _not_ be closed.
