### ISSUE TITLE
Is it possible to add subdomains to redirects?

### ISSUE THREAD

**Issue by Cjschmidt** [skybrud/Skybrud.Umbraco.Redirects#60]
Example:

domain1.domain.com/subpage=> newdomain.com/subpage1
domain2.domain.com/subpage=> newdomain.com/subpage2

Currently I can't find this feature

**Comment by abjerner** [comment]
Hi @Cjschmidt,

This feature didn't make it to the first release for Umbraco 8. I just pushed a new release, and if I understand your question correctly, it is now supported:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v2.0.1
