### ISSUE TITLE
Introduce cache layer

### ISSUE THREAD

**Issue by abjerner** [skybrud/Skybrud.Umbraco.Redirects#62]
The HTTP module will make a handful of SQL queries per request (think it's four at worst). With a site that receives many 404 request, this may affect performance of the database and site.

For a number of reasons, it may be ideal to have a cache layer in front of the database. A cache layer will reduce the amount of calls to the database considerably, and also allow us to do new things - eg. adding support for forced redirects.

**Comment by ronaldbarendse** [comment]
As commented in https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/59#issuecomment-559696622, caching won't make it faster, especially if you have a lot of redirects (as all redirects must be retrieved from the database first).

If Regex redirects get supported, those might indeed need to be cached, as you can't query them directly in the database (based on the current URL) 😉

**Comment by abjerner** [comment]
@ronaldbarendse thanks for the feedback. I can't remember my exact thoughts when I created this issue, so maybe the priority label can be discussed. But I think it's still something that at least is worth investigating.

However as things are now, it's not something I currently have the time to look into 😮
