### ISSUE TITLE
Add automatic migration to v2

### ISSUE THREAD

**Issue by ronaldbarendse** [skybrud/Skybrud.Umbraco.Redirects#64]
I've just upgraded a site from Umbraco 7 to 8 and updated this package to v2. As the `SkybrudRedirects` table schema is alterned, none of the redirects worked and neither was adding new redirects from the backoffice (because of SQL errors).

It would be nice if this table was automatically migrated as part of the v1 to v2 update. I've now done this with the following SQL script, so it can at least be manually migrated (feel free to add this to the documentation):

```sql
BEGIN TRANSACTION;

-- Rename existing table and remove primary key
EXEC sp_rename 'SkybrudRedirects', 'SkybrudRedirectsV7';
ALTER TABLE [SkybrudRedirectsV7] DROP CONSTRAINT [PK_SkybrudRedirects];

-- Optionally delete existing migration, so table can be re-created (make sure to run Umbraco after this)
DELETE FROM [umbracoKeyValue] WHERE [key] = 'Umbraco.Core.Upgrader.State+Skybrud.Umbraco.Redirects' AND [value] = '2.0.0-alpha001';

-- Migrate redirects
SET IDENTITY_INSERT [SkybrudRedirects] ON;
INSERT INTO [SkybrudRedirects] (
	[Id],
	[Key],
	[RootId],
	[RootKey],
	[Url],
	[QueryString],
	[DestinationType],
	[DestinationId],
	[DestinationKey],
	[DestinationUrl],
	[Created],
	[Updated],
	[IsPermanent],
	[IsRegex],
	[ForwardQueryString]
) SELECT
	[RedirectId],
	[RedirectUniqueId],
	[RootNodeId],
	-- RootKey
	CASE WHEN [RootNodeId] = 0 THEN '00000000-0000-0000-0000-000000000000' ELSE (SELECT [uniqueId] FROM [umbracoNode] WHERE [id] = [RootNodeId]) END,
	[Url],
	[QueryString],
	[LinkMode],
	[LinkId],
	-- DestionationKey
	CASE WHEN [LinkId] = 0 THEN '00000000-0000-0000-0000-000000000000' ELSE (SELECT [uniqueId] FROM [umbracoNode] WHERE [id] = [LinkId]) END,
	[LinkUrl],
	DATEADD(S, [Created], '1970-01-01'),
	DATEADD(S, [Updated], '1970-01-01'),
	[IsPermanent],
	[IsRegex],
	[ForwardQueryString]
FROM 
	[SkybrudRedirectsV7];

SET IDENTITY_INSERT [SkybrudRedirects] OFF;

-- Show migrated redirects and remove old table
SELECT * FROM SkybrudRedirects;
DROP TABLE [SkybrudRedirectsV7];

COMMIT TRANSACTION;
```

**Comment by abjerner** [comment]
@ronaldbarendse thanks a lot posting this 👍 

I think I started out on the V8 version of this package before Umbraco made it possible to upgrade from V7 to V8, so the redirects package wasn't intended to handle this. Which is kinda bad now that there is an upgrade path.

One of the things I'm probably going to look at next is import and export functionality, so I had thought about creating a migration that renames the old table, exports the rows, and then imports them in the new table. Doing this with an SQL script could possibly be smoother, so I'll look into that 😉

**Comment by ronaldbarendse** [comment]
I've successfully migrated more than 100 redirects using this script and this seems to be the easiest/fastest way.

I'm not sure if you can explicitly target v7 to v8 migrations, but the existing `CreateTable` migration could be updated to run this script when the table already exists (and if it's the v7 schema):

https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/f8470d83a92da666936293e00cf07786fb092a7f/src/Skybrud.Umbraco.Redirects/Migrations/CreateTable.cs#L11

**Comment by abjerner** [comment]
Hi @ronaldbarendse 

This was something that the Umbraco 8 package *should* have supported, but as I've lacked the time to look into this, and as we're now moving towards Umbraco 9, I think it's too late to add this feature. I'm therefore closing the issue.
