### ISSUE TITLE
Querystring is not retained on a new redirect

### ISSUE THREAD

**Issue by madden-tom** [skybrud/Skybrud.Umbraco.Redirects#65]
When I add a redirect (version 2.0.3, Umbraco 8.5.4, latest Chrome) the querystring value is lost as soon as I press Submit.

Forward query string is enabled.

Adding a link with a querystring in the multi url picker in the same version of Umbraco does work.

![image](https://user-images.githubusercontent.com/1767232/75261307-b8a0e900-57e2-11ea-9547-0a41bacc6c00.png)

![image](https://user-images.githubusercontent.com/1767232/75261340-c48cab00-57e2-11ea-8b3f-5ec1f024ebec.png)

**Comment by madden-tom** [comment]
Just to add, this happens when I enter the querystring directly into the querystring field, but it also happens if you have pasted the whole link into the link field, submit this (and it is retained up to this point), but if you click Edit, then Submit (without changing anything), then the Querystring is lost (when you click submit).

**Comment by abjerner** [comment]
Hi @madden-tom and thanks for reporting 👍

The overlay used for picking the destination of the redirect comes from Umbraco. The **Anchor / querystring** field was added through a PR at some point in Umbraco 7, so it has never really worked in the redirects package. I guess I also overlooked this part when upgrading the package to Umbraco 8.

As the query string or anchor/fragment may be specified either as part of the URL or explicitly via the **Anchor / querystring** field (or even both), there is a number of different scenarios that should be taken into account.

The redirects package contains a `parseUmbracoLink` function that I'm using for converting the link object received from Umbraco's overlay into something the redirects package can understand. I've tried to update that function to match these scenarios: https://github.com/skybrud/Skybrud.Umbraco.Redirects/commit/3fa6aa5d0b9f7ba80210c0b9b7da0226e51e4b01

It probably needs a bit more testing, and it only handles the link object received from Umbraco's overlay, so there are still other parts of the package that needs to be updated as well. But it at least serves as a starting point - then I can have another go at it when I can find some more time 😉

**Comment by ronaldbarendse** [comment]
I've just encountered the same, both with external/manual links and when selecting content. Manually changing the destination URL within the database to include the query string works though (and when query string forwarding is enabled, these are even merged).

While a fix is implemented, the query string/anchor field can be easily hidden by adding `hideAnchor: true` to:
https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/1b533e27bfd2ec62e0f8ce345990231e17b0cb36/src/Skybrud.Umbraco.Redirects/App_Plugins/Skybrud.Umbraco.Redirects/Scripts/Controllers/Editors/Destination.js#L6

**Comment by ronaldbarendse** [comment]
Just like the Multi URL Picker, the query string/anchor should be stored seperately (e.g. `DestinationQueryString` column), so it can be merged with the current content/media URL in the right culture: https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/63#issuecomment-627409023.

**Comment by wvduffelen** [comment]
Is there any update on this issue? When picking a node and adding the query string the query string is being removed. When you don't pick a page and only fill the 'Link' field it works. For now it's a workaround but not the best option. A client of ours have multiple filtered views and cannot pick the page and add the query string!

Just tested some more. When the full URL (with query) is pasted in the 'Link' field it works. If you edit the link after this the query string is filled within the 'Anchor / querystring'. When you fill a query string in the 'Anchor / querystring' it's removed when saved.

This doesn't work
![afbeelding](https://user-images.githubusercontent.com/34159733/118959104-4b86ef80-b962-11eb-83f0-03ac9adb28fe.png)

This works (when saved it's shown as above)
![afbeelding](https://user-images.githubusercontent.com/34159733/118959054-40cc5a80-b962-11eb-9ce8-5d72c3babc5d.png)

**Comment by abjerner** [comment]
Hi @madden-tom (and others)

For the [**v2.1.2**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v2.1.2) release, I added better support for query strings and fragments. This should thereby also address the problem described in this issue.

Could you test and confirm whether this is now the case?
