### ISSUE TITLE
GetOutboundRedirect extension not working in v8?

### ISSUE THREAD

**Issue by rpjengaard** [skybrud/Skybrud.Umbraco.Redirects#66]
Hi Bjerner,

if i use the extensionmethod GetOutboundRedirect on my content it just returns null. I tried this

`var test = request.Content.Value("skyRedirect");` and this returns

`{
  "permanent": true,
  "destination": {
    "id": 0,
    "key": "00000000-0000-0000-0000-000000000000",
    "url": "https://www.limbo.works/",
    "type": "url"
  }
}`

If i try to mimic the [code](https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/d98f959d114c01e983dd900d42bbe212a2749e54/src/Skybrud.Umbraco.Redirects/Extensions/PublishedContentExtensions.cs#L39) by doing this `OutboundRedirect test = request.Content.Value("skyRedirect") as OutboundRedirect;` i get `null`.

Umbraco version is v8.4.0 and Redirect package is v2.0.3

**Comment by abjerner** [comment]
Should be fixed in [**v2.0.4**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v2.0.4) :tada:
