### ISSUE TITLE
Unable to load redirects

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#7]
I installed the package v.0.2.2 via NuGet and added the dashboard.

After refreshing browser the dashboard is added, but I get the following error:
![image](https://cloud.githubusercontent.com/assets/2919859/22314832/8e5ae124-e363-11e6-937f-2f332e3409a3.png)

Tested in Umbraco version 7.5.8 and on Umbraco Cloud, but local - so the db is SQL CE.

**Comment by abjerner** [comment]
Thanks for reporting.

I haven't tested with Umbraco Cloud, but I have tested locally SQL CE without any problems.

Can you see more details about the error? Either by using Chrome to inspect the failed HTTP call (I can't remember whether there something useful in the JSON) or the the Umbraco log?

**Comment by bjarnef** [comment]
I didn't seem any errors in the logs, but maybe it is an issue, when using Courier?
So this project was using Courier v.3.0.4 ...

I have uninstalled the package again is this project and installed UrlTracker since it is going live soon.. but I could try installing the package on another project and see if there is a more specific error message in the request.

**Comment by abjerner** [comment]
I'm not using Contour, but if you have installed the package using NuGet, I'm assuming you have installed it locally, so with what I know about Contour, it shouldn't do any difference locally.

Anyways, I can see that I need to add some more error handling and logging. Could your try something like:

```C#
RedirectsRepository repo = new RedirectsRepository();

var array = repo.GetRedirects();
```

The API controller will call the `GetRedirects` method in the `RedirectsRepository` class, so if the API call fails, this method should throw some kind of exception.

**Comment by bjarnef** [comment]
I have checked the error message further.
It returns `Failed to load resource: the server responded with a status of 500 (Internal Server Error)` in `/umbraco/backoffice/api/Redirects/GetRedirects?limit=10&page=1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

Clicking this link returns the stacktrace:

```
{"Message":"An error has occurred.","ExceptionMessage":"The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.","ExceptionType":"System.InvalidOperationException","StackTrace":null,"InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Could not load type 'Skybrud.Essentials.Time.EssentialsDateTime' from assembly 'Skybrud.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.","ExceptionType":"System.TypeLoadException","StackTrace":"   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)\r\n   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()\r\n   at System.Reflection.RuntimeMethodInfo.GetParameters()\r\n   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetCallbackMethodsForType(Type type, List`1& onSerializing, List`1& onSerialized, List`1& onDeserializing, List`1& onDeserialized, List`1& onError)\r\n   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveCallbackMethods(JsonContract contract, Type t)\r\n   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)\r\n   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteStartArray(JsonWriter writer, Object values, JsonArrayContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n   at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"}}
```

![image](https://cloud.githubusercontent.com/assets/2919859/22352429/691f0ac0-e41c-11e6-8b80-cd3973ea1328.png)

**Comment by abjerner** [comment]
Thanks - that helped a bit. Although it also doesn't make sense.

According to the stack trace, your solution is missing the `Skybrud.Essentials.Time.EssentialsDateTime` class from the `Skybrud.Essentials` package.

The NuGet package has a dependency for our `Skybrud.LinkPicker` package, which again has as dependency for the missing `Skybrud.Essentials`. If you have installed the redirects package via NuGet, both these dependencies should have been installed. Can your check your `package.config` and/or project references and confirm whether this is the case?

**Comment by bjarnef** [comment]
The /bin folder contains these Skybrud assemblies:

![image](https://cloud.githubusercontent.com/assets/2919859/22352781/e399abba-e41d-11e6-86cd-897e6fd60bda.png)

and my packages.config

![image](https://cloud.githubusercontent.com/assets/2919859/22352827/0645d38c-e41e-11e6-9920-fd098671dea6.png)

**Comment by bjarnef** [comment]
Is this the expected version for `Skybrud.Essentials.dll`

![image](https://cloud.githubusercontent.com/assets/2919859/22352882/4aad5a22-e41e-11e6-8a2d-9e34e043c8d5.png)

**Comment by bjarnef** [comment]
The latest version of `Skybrud.Essentials` on NuGet is 1.0.7, but it installs version 1.0.0 ... is `EssentialsDateTime` added in a later version?

**Comment by abjerner** [comment]
Nope, the `Skybrud.Essentials` DLL is too old. The `EssentialsDateTime` class was added after `v1.0.0`, but is part of `v1.0.7`.

I can see that the redirects package has a dependency for an older version of the `Skybrud.LinkPicker` package, which again has a dependency for an older version of the `Skybrud.Essentials` package. Which is why the code fails. It should work if you update `Skybrud.Essentials` to the newest version ;)

I actually updated the dependencies [yesterday](https://github.com/skybrud/Skybrud.Umbraco.Redirects/commit/8918e47fb8a0a55b0b2758d5b6da14f1e7666981), but haven't released it yet since I haven't had the time to ... test it yet. It will be part of the next release, which hopefully will be out over the weekend.

**Comment by bjarnef** [comment]
Yes, it fixed the error after updating `Skybrud.Essentials` to version `1.0.7`

I guess the missing localization is just the missing part, you also added in the commit yesterday?

![image](https://cloud.githubusercontent.com/assets/2919859/22353390/6f8a486c-e420-11e6-8d55-b3e58e50a256.png)

I was wondering what `Skybrud.Umbraco.GridData` is used for? or only because it is a dependency of `Skybrud.LinkPicker`?

**Comment by abjerner** [comment]
Yes, the missing localization was fixed yesterday. With the latest release, there is a translation for `en-GB`, but as far is I remember, Umbraco will look for `en-US` by default. So the commit yesterday adds translations for both languages.

You're also correct regarding the GridData package. `Skybrud.Umbraco.Redirects` uses components from `Skybrud.LinkPicker`, which again has a dependency for `Skybrud.Umbraco.GridData`. I rather avoid that extra dependency, so I might have a look at copying some of our link picker logic, and then skip both dependencies - but I haven't really look into that yet.

**Comment by abjerner** [comment]
I ended of dropping the dependency for `Skybrud.LinkPicker`, which the list of dependencies a bit more single.

I've also pushed a new release with the updated dependencies here: https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v0.2.3
