### ISSUE TITLE
Prefer explicit DB schema definitions over automatic DTOs

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#73]
At the moment to migration use a DTO class to create the table:
https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/Migrations/CreateTable.cs

However it would be preferable to explicit DB schema definitions if the table change later, e.g. a column is removed.

See some relevant isssues from Vendr wishlists:
https://github.com/vendrcontrib/vendr-wishlists/issues/5
https://github.com/vendrcontrib/vendr-wishlists/issues/1

For example for Vendr Reviews the migration looks like this:
https://github.com/vendrcontrib/vendr-reviews/tree/dev/src/Vendr.Contrib.Reviews/Migrations/V_1_0_0

**Comment by abjerner** [comment]
Hi @bjarnef,

The migration for creating the database table use [RedirectItemSchema](https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/Models/Database/RedirectItemSchema.cs), and not [RedirectItemDto](https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/Models/Database/RedirectItemDto.cs). While a bit different from Matt's approach for Vendr, this should this still be a line with creating an immutable migration, as the `RedirectItemSchema` class won't change.


Or am I missing something?

**Comment by bjarnef** [comment]
@abjerner yeah, but [RedirectItemSchema](https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/Models/Database/RedirectItemSchema.cs) is basically a DTO class as well although the name doesn't identicate that.

It might work when RedirectItemSchema is not changing, but it a column later is removed and the column type is changed, it guess it would create a different class, otherwise I think it could cause errors if the initial 1.0.0 migration hasn't run.

So I guess the approach @mattbrailsford use in Vendr might make it easier to change a few columns later, but honestly I haven't tried this and how it works with the approach with the schema class and then later modify some columns.

**Comment by abjerner** [comment]
I think either approach is correct. Using a schema class may require less code, whereas Matt's approach of specifying the columns individually may give some more flexibility and control. The Umbraco documentation describes the use of schema classes here: https://our.umbraco.com/Documentation/Extending/Database/#schema-class-and-migrations

The general idea is that if you make changes to the database table, you add a new migration for those changes. The schema class is only used for creating the table, and will therefore stay the same hereafter. You are not allowed to change this going forward if the migrations should stay immutable.

In the case with Matt's create table migrations, they should also not change over time. If Matt needs to add additional changes to the tables in the future, those changes should also happen via a new migration. Changing the original migration would break the "immutability".

If I for the redirects package were to remove a column in the future, the initial migration should still create the table including that particular column. I should instead then create a new migration that removes the column. That ensures that the migrations stay immutable. That also means that if you install the redirects package in a blank Umbraco solution, the column will be added initially when the table is created via the first migration, but then removed right after by the second migration.

It's fine to update the DTO class though, as that is strictly used for data transferring. The schema class is never used for data transfer.
