### ISSUE TITLE
Adjust padding in table header

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#75]
Using latest v2.0.5 on Umbraco v8.8.1 it looks the table header is a bit off compared to core redirects dashboard.

![image](https://user-images.githubusercontent.com/2919859/97541072-d4d5d500-19c4-11eb-94dc-93b280efc1da.png)

![image](https://user-images.githubusercontent.com/2919859/97541119-e919d200-19c4-11eb-8963-93ff9725e4b7.png)

When disabling the css overwritting to padding from `umb-table-cell` class it looks a bit nicer.

![image](https://user-images.githubusercontent.com/2919859/97541200-0cdd1800-19c5-11eb-9eaf-810114e4bb26.png)

**Comment by bjarnef** [comment]
It looks like the cells in first column in Umbraco redirects table has the class `not-fixed`.

**Comment by abjerner** [comment]
Thanks for the input @bjarnef - and sorry for the lack of reply 👍 

I think Umbraco's styling may have changed a bit over time, which may be why the first column looks a bit off.

The list is currently using `<div>`'s along with the `umb-table` classes, which also causes some issues with columns being cropped at weird places. The inbound redirects property editor is using a regular table instead, which I may switch to for the dashboard as well.

**Comment by bjarnef** [comment]
Actually it seems this part just overwrite the default padding on first table column. https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/App_Plugins/Skybrud.Umbraco.Redirects/Styles/Styles.less#L36

Not sure if it need this. I would probably keep the `<div>` to keep it consistent with Umbraco UI and optimize it for the most recent supported Umbraco versions, although it might cause some minor styling issues for older v8 versions.

**Comment by abjerner** [comment]
Thanks again @bjarnef 👍 

I may still switch to using `<table>` at a later point, as I feel that gives me more control (as I'm not a frontender). But at least for now, I've added a bit of padding to the first column as suggested 😉
