### ISSUE TITLE
Add shortcut to close button

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#76]
The close button in the redirects overlay here, seems to be missing `shortcut="esc"`.
https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2/latest/src/Skybrud.Umbraco.Redirects/App_Plugins/Skybrud.Umbraco.Redirects/Views/Dialogs/Redirect.html#L32

With this added the overlay can be closed using `esc` key 👍

**Comment by abjerner** [comment]
Thanks. This is now part of the latest release: https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v2.0.7
