### ISSUE TITLE
Accessibility enhancements for buttons

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#77]
A few places a noticed `<a>` elements for buttons are used instead of actually `<button>` element which are preferred unless it is an actual link.
https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/v2.0.5/src/Skybrud.Umbraco.Redirects/App_Plugins/Skybrud.Umbraco.Redirects/Views/Editors/Inbound.html#L10-L15

So we can for example use something like the following instead. Some places it might need to use e.g. `btn-reset` or `btn-link` classes from Umbraco.

```
<button type="button" ng-click="addRedirect()" class="btn btn-success">
      <localize key="redirects_addNewRedirect">Add new redirect</localize>
</button >
<button type="button" ng-click="updateList()" class="btn btn-default">
     <localize key="redirects_reload">Reload</localize>
</button >
```

**Comment by abjerner** [comment]
Thanks 👍 

This and other uses of `<a>` have now been replaced with `<button>` in the latest release: https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v2.0.7
