### ISSUE TITLE
Where is RedirectsRepository?

### ISSUE THREAD

**Issue by andreasengstr** [skybrud/Skybrud.Umbraco.Redirects#78]
According to this: https://packages.skybrud.dk/skybrud.umbraco.redirects/docs/#installation 
the Skybrud redirect package "Includes a RedirectsRepository for managing the redirects from your own code".

However, I cannot not see any information in the documentation on how to manage redirectes from my own code?

We are using Umbraco 8.9 as a head-less CMS and would like to read/fetch redirect information from our custom non-MVC controllers, is that even possible with Skybrud Redirect package?

**Comment by abjerner** [comment]
@andreasengstr Sorry - this is a leftover from the Umbraco 7 version. It's called `RedirectsService` in Umbraco 8 (but you may wish to refer to `IRedirectsService` if you're using dependency injection).

Here's an example of how we're using it in our own SPA setup:

https://github.com/skybrud/Skybrud.Umbraco.Spa/blob/master/src/Skybrud.Umbraco.Spa/SpaRequestHelper.Flow.cs#L230

**Comment by andreasengstr** [comment]
OK, thanks!
Btw, will Skybrud Redirects be available for the coming .NET Core version of Umbraco?

**Comment by abjerner** [comment]
@abjerner most likely yes, but I don't know for sure yet. I haven't seen any dates for when the .NET Core version will be out, so it might still be a bit out in the future.
