### ISSUE TITLE
Cannot see redirect items on content item

### ISSUE THREAD

**Issue by andreasengstr** [skybrud/Skybrud.Umbraco.Redirects#79]
When adding a redirect property editor on a content item it is possible to add redirect items (and they show up in the redirects dashboard) but they are not visible on the content item itself, all that I can see is the "Add new redirect" and "Reload" buttons but not any redirects, pressing Reload does not change anything.

Umbraco version is 8.9.0

**Comment by CasperTDK** [comment]
Same here after updating to 8.7.0. I can not see any obvious errors in the console. However, Umbraco did bump angular in this version:
_"Bump angular from 1.7.9 to 1.8.0 in /src/Umbraco.Web.UI.Client"_

https://our.umbraco.com/download/releases/870

**Comment by abjerner** [comment]
Thanks for the feedback 👍 

Yes, the Angular version bump broke the view of the property editor as it was still using an Angular directive through an auto-closing element. I've pushed a new release that fixes this: https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v2.0.6
