### ISSUE TITLE
Redirects not working on prod enviroment

### ISSUE THREAD

**Issue by helenahedstrom** [skybrud/Skybrud.Umbraco.Redirects#80]
Redirects work perfectly when using it locally, but not in prod. One of the things that differs on local and prod enviroment is domains.

We host on Azure and use custom domains there as well as in Umbraco. However the redirect doesn't seem to trigger no matter which domain I try. 

This issue might have to do with our configurations but if you could help me I would appreciate it. Do I need any special configuration? Is there a way to tell what domain the original url field points to? Is there any more info you can give me that can help with troubleshooting?

Skybrud redirect version 2.0.6
Umbraco version 8.1.4

**Comment by abjerner** [comment]
Hi @helenahedstrom,

Sorry I missed your question.

When installing the package locally, it adds a HTTP module to your Web.config file. In our own hosting setup, we typically deploy changes to the Web.config file manually, so if you're doing the same, you may have missed adding the HTTP module in the Web.config file on Azure.

In the `<system.webServer>` element, look for the `<modules>` element. The element and children should look something like the snippet below - the two lines with **RedirectsModule** being the important ones:

```xml
<modules runAllManagedModulesForAllRequests="true">
            <remove name="WebDAVModule" />
            <remove name="UmbracoModule" />
            <remove name="ScriptModule" />
            <remove name="FormsAuthentication" />
            <remove name="ImageProcessorModule" />

            <add name="UmbracoModule" type="Umbraco.Web.UmbracoModule,Umbraco.Web" />
            <add name="ScriptModule" preCondition="managedHandler" type="System.Web.Handlers.ScriptModule, System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
            <!-- Needed for login/membership to work on homepage (as per http://stackoverflow.com/questions/218057/httpcontext-current-session-is-null-when-routing-requests) -->
            <add name="FormsAuthentication" type="System.Web.Security.FormsAuthenticationModule" />
            <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />
            <remove name="RedirectsModule" />
            <add name="RedirectsModule" type="Skybrud.Umbraco.Redirects.Routing.RedirectsModule, Skybrud.Umbraco.Redirects" />
            <remove name="ClientDependencyModule" />
            <add name="ClientDependencyModule" type="ClientDependency.Core.Module.ClientDependencyModule, ClientDependency.Core" />
        </modules>
```

I hope that helps 😉

**Comment by helenahedstrom** [comment]
Yes, that solved it!

Thank you so much and have a great weekend!

Regards,
Helena
