### ISSUE TITLE
Can't add redirect in Umbraco 7.15.6

### ISSUE THREAD

**Issue by timeverts** [skybrud/Skybrud.Umbraco.Redirects#83]
Hi,

I have installed version 1.0 of the package in an Umbraco 7.15.6. The package seems to have installed okay, but when I attempt to add a redirect by entering the details and then clicking the green 'Add Redirect', it responds with a 404.

Details of the exception are:
```
{"Message":"No HTTP resource was found that matches the request URI 'http://mysite.localhost/umbraco/backoffice/api/Redirects/AddRedirect?forward=false&linkId=2194&linkMode=content&linkName=Staying+Safe&permanent=false&regex=false&rootNodeId=0&url=%2Ftest'.","MessageDetail":"No action was found on the controller 'Redirects' that matches the request."}
```

**Comment by abjerner** [comment]
Hi @timeverts,

I can see that the `linkUrl` parameter is missing in the URL.

The package is using Umbraco's link picker for selecting the redirect destination. If you're picking a node in the content tree, Umbraco will make a request to it's own API to determine the URL of the selected node. Depending on the page and your setup, this request may not have finished when you click the Submit button in the link picker overlay. And if so, the redirect will not have a valid destination URL (hence `linkUrl` being missing).

I've typically only seen this when working in a dev environment locally, as there usually is a bit of latency when the DB is hosted elsewhere. But it can also happen in the live environment if you're super quick, or the request for some reason takes a bit longer than usual.

Could you check whether this could be the reason?

![image](https://user-images.githubusercontent.com/3634580/111765851-2532ce00-88a5-11eb-8141-3e6c9412284c.png)

**Comment by timeverts** [comment]
Hi @abjerner. 
I'm sorry. Turns out you were correct! 
I waited a bit longer for the URL to properly populate and the the redirect could be added.
Thanks for taking the time to respond though.
