### ISSUE TITLE
Skybrud.Umbraco.Redirects.Core package without App_Plugins folder

### ISSUE THREAD

**Issue by jesperweber** [skybrud/Skybrud.Umbraco.Redirects#84]
Hi, 

We are using the Skybrud.Umbraco.Redirects package on multiple projects and like the package. 

However we we would also like to use the package in class library projects. To avoid the App_Plugins folder in the class library projects, it would be cool with a Skybrud.Umbraco.Redirects.Core package that only holds the dll's without any frontend and view files.

**Comment by abjerner** [comment]
Hi @jesperweber 

Splitting up the package puts a bit more work on my end when creating new releases, so at least for now, we won't be splitting up the package.
