### ISSUE TITLE
Redirect not working locally or on azure

### ISSUE THREAD

**Issue by khraibani** [skybrud/Skybrud.Umbraco.Redirects#85]
Redirects not working locally, or in prod. I have checked the web.config it has 'RedirectsModule' on both environments 
```
<remove name="RedirectsModule" />
<add name="RedirectsModule" type="Skybrud.Umbraco.Redirects.Routing.RedirectsModule, Skybrud.Umbraco.Redirects" /> 
```

- The weird thing is some of the URL that I have added previously are redirecting fine. Just when I add a new one.
- I have tried clearing my browser cache, used a separate browser that I haven't visited the page from with no luck.
- I have checked if there already a redirect in the Umbraco Url Redirect Management 
- I have disabled Umbraco Url Redirect Management

If you could help me I would appreciate it.

Skybrud redirect version 2.0.7
Umbraco version 8.6

![Screenshot 2021-04-19 102901](https://user-images.githubusercontent.com/4085627/115214104-1769a600-a0fa-11eb-98f3-6e4f2b410b6e.jpg)

**Comment by abjerner** [comment]
Hi @khraibani,

Is this perhaps the original URL? https://quolux.com/blog/posts/10-steps-for-giving-effective-constructive-feedback

The redirects module will only kick in if the server responds with a 404 error code. For instance, if the server responds with a 200 status code (eg. if a page exists at that URL), the redirects module will not do anything, and Umbraco will instead show that page.

I hope this make sense 😉

**Comment by khraibani** [comment]
@abjerner I fell for this one! Guess its a Monday 🤐
