### ISSUE TITLE
Mark unpublished or deleted destination pages in the dashboard

### ISSUE THREAD

**Issue by tnielsenskybruddk** [skybrud/Skybrud.Umbraco.Redirects#86]
A customer has suggested that redirects that link internally is marked as inactive in the dashboard if the destination page is either unpublished or deleted.

**Comment by abjerner** [comment]
Hi @tnielsenskybruddk 

This requires a lot of restructuring to implement in Umbraco 8, so I'm closing the issue as we're moving towards Umbraco 9.

I had this issue in mind when rewriting the Umbraco 9 package, so it's already supported there.
