### ISSUE TITLE
Umbraco 9

### ISSUE THREAD

**Issue by andersburla** [skybrud/Skybrud.Umbraco.Redirects#87]
So Umbraco 9 is moving forward. Is there plans/time to make a version of this package for Umbraco 9? Also with multi language/variants support 😊

Kind regards
Anders

**Comment by abjerner** [comment]
Hi @andersburla 

I've made a lot of progress in the [**v3/main**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/tree/v3/main) branch. I work on it a bit here and there when I can find the time, so I don't have an ETA at the moment.

**Comment by andersburla** [comment]
Thanks for the update. Nice that its coming along.
