### ISSUE TITLE
/media redirects throw 500's on non local environments

### ISSUE THREAD

**Issue by ja0b** [skybrud/Skybrud.Umbraco.Redirects#88]
Hi 👋,

I'm using Umbraco 8.13.0 and on my local all works as expected but on the dev environment (web app) I have some odd behaviour:

/trololo.pdf = works ✅
/fake/trololo.pdf => works ✅
/media/trololo => works ✅
/media/trololo.pdf => doesn't work ❌

Anything with an extension inside the /media path throws a 500 but if you disable custom errors ( ⚠️ <customErrors mode="Off"...) then the redirects works as expected. I have no idea if this is an Umbraco thing or is the package.

Any ideas?🤔

Thanks! 👍
Ale

**Comment by abjerner** [comment]
Hi @ja0b 

I've tried to do a few tests for this, but it's not something I can reproduce the error.

If you're unable to see the exception in the YSOD, you may still be able to find something in the Umbraco log, which could be useful for finding the cause of the issue.
