### ISSUE TITLE
When url without www is used redirecting goes wrong

### ISSUE THREAD

**Issue by remkovb** [skybrud/Skybrud.Umbraco.Redirects#99]
We have an original url like /dance
This redirects to filter page with alle kinds of query parameters in url.

for https://www.oururl.com/dance this works perfectly. For https://oururl.com/dance the destination url gets stripped down and doesn’t work anymore. Looks like there is some kind of step in between that changes the destination url somehow.

**Comment by abjerner** [comment]
Hi @remkovb 

Could you please provide some more information about your issue? Such as:

- What version of Umbraco and this package are you using?

- If there are query string parameters in the inbound URL, could you provide better examples of these?

- Can you share how the redirect in question is saved in the database? Eg. a screenshot or similar. Feel free to blank the domain or similar - it's just so I can get the general idea of how the redirect is set up
